'use client';
import {renderEmail} from '@/lib/pastoral/email-design';
import {BroadcastDesigner} from './broadcast-designer';
import {useEffect,useState,type ReactNode} from 'react';
import {Mail,MessageSquare,Plus,Clock,Send,Copy,Check,AlertCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {audience,directoryGroups,broadcastStatus,type Broadcast,type CommunicationsState,type DeliveryConnection} from '@/lib/pastoral/communications';
import type {Action,Channel} from '@/lib/pastoral/model';
const date=(value:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))+' CT';
type Props={state:CommunicationsState;busy:boolean;run:(a:Action)=>Promise<boolean>;refresh:()=>Promise<void>;request:(path:string,init?:RequestInit)=>Promise<Response>;approvals:ReactNode;inbox:ReactNode;pending:number};
export function CommunicationsPanel({state,busy,run,refresh,request,approvals,inbox,pending}:Props){
 const [tab,setTab]=useState('Broadcast queue'),[filter,setFilter]=useState('All'),[channel,setChannel]=useState('all'),[composer,setComposer]=useState<Broadcast|'new'|null>(null),[review,setReview]=useState<string|null>(null),[connection,setConnection]=useState<DeliveryConnection|null>(null),[connectionError,setConnectionError]=useState(''),[composeChannel,setComposeChannel]=useState<Channel>('email');
 useEffect(()=>{let active=true;async function load(){try{const r=await request('/api/delivery-connection',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to check delivery.');if(active){setConnection(data);setConnectionError('');}}catch{if(active){setConnection(null);setConnectionError('Delivery connection could not be checked.');}}}void load();const timer=setInterval(()=>{void refresh();void load();},30000);return()=>{active=false;clearInterval(timer);};},[request,refresh]);
 const all=state.broadcasts??[],groups=directoryGroups(state),broadcast=all.find(b=>b.id===review);
 const list=all.filter(b=>(channel==='all'||b.channel===channel)&&(filter==='All'||filter==='Drafts'&&b.status==='draft'||filter==='Scheduled'&&['Scheduled','Queued','Sending'].includes(broadcastStatus(b))||filter==='Sent'&&['Sent','Finished with skips'].includes(broadcastStatus(b))||filter==='Attention'&&['Needs attention','Not sent'].includes(broadcastStatus(b))));
 if(composer)return <BroadcastDesigner key={composer==='new'?'new':composer.id} value={composer==='new'?undefined:composer} initialChannel={composeChannel} state={state} busy={busy} run={run} request={request} connection={connection} close={()=>{setComposer(null);setTab('Broadcast queue');}}/>;
 return <><div className="section-tabs" role="tablist" aria-label="Communications views">{['Email','Text messages','Broadcast queue','Approvals','Conversations'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>{if(t==='Email'||t==='Text messages'){setComposeChannel(t==='Email'?'email':'sms');setComposer('new');}else setTab(t);void refresh();}}>{t}{t==='Approvals'&&pending>0&&<span className="count-pill">{pending}</span>}</button>)}</div>{tab==='Approvals'?approvals:tab==='Conversations'?inbox:<><div className="broadcast-toolbar"><div className="queue-filters">{['All','Drafts','Scheduled','Sent','Attention'].map(t=><button className={filter===t?'active':''} key={t} onClick={()=>{setFilter(t);void refresh();}}>{t}</button>)}</div><div className="flex gap-2"><select aria-label="Filter broadcasts by channel" className="plain-select" value={channel} onChange={e=>setChannel(e.target.value)}><option value="all">Email & text</option><option value="email">Email</option><option value="sms">Text message</option></select><Button onClick={()=>setComposer('new')}><Plus size={17}/>New broadcast</Button></div></div><div className="delivery-connections"><span><MessageSquare size={14}/>{connection?connection.sms?'Text connected':'Text not connected':'Checking text…'}</span><span><Mail size={14}/>{connection?connection.email?`Email · ${connection.emailFrom}`:'Amazon SES setup needed':'Checking email…'}</span>{connectionError&&<span role="alert">{connectionError}</span>}</div>
 {connection&&!connection.email&&<div className="email-setup-note"><Mail size={19}/><div><strong>Email drafts are ready to use.</strong><p>Sending from info@1ag.tv will be available once Amazon SES is connected. Drafts stay saved here.</p></div></div>}
 <section className="broadcast-list">{list.length?list.map(b=><article key={b.id} className="broadcast-row"><span className={`broadcast-icon ${b.channel}`}>{b.channel==='email'?<Mail size={21}/>:<MessageSquare size={21}/>}</span><div className="broadcast-summary"><button onClick={()=>setReview(b.id)} className="font-semibold text-left">{b.subject}</button><p>{b.channel==='email'?'Email':'Text message'} · {[...b.groupIds.map(id=>groups.find(g=>g.id===id)?.name??'Tag removed'),...(b.personIds??[]).map(id=>state.people.find(p=>p.id===id)?.name??'Contact removed')].join(', ')}</p><small><Clock size={12}/>{date(b.scheduledAt)}{b.targets.length>0&&` · ${b.targets.filter(t=>t.status==='sent').length}/${b.targets.length} accepted by provider`}</small></div><span className={`queue-status ${broadcastStatus(b)==='Sent'?'sent':''}`}>{broadcastStatus(b)}</span><Button variant="outline" size="sm" onClick={()=>b.status==='draft'?setComposer(b):setReview(b.id)}>{b.status==='draft'?'Edit draft':'View'}</Button>{b.status==='draft'&&<Button size="sm" onClick={()=>setReview(b.id)}>Review</Button>}</article>):<div className="directory-empty"><Send size={30} className="mx-auto mb-4 text-teal-700"/><h2>{all.length?'No broadcasts match':'Your broadcast queue'}</h2><p className="mt-2">Create an email or text, choose your groups, then review and schedule it.</p><Button className="mt-5" onClick={()=>setComposer('new')}>Create broadcast</Button></div>}</section><p className="text-xs muted mt-5">Scheduled broadcasts run while this page is closed. Sending follows your workflow pause and sending hours. “Sent” means accepted by the provider, not confirmed read.</p></>}
 {broadcast&&<BroadcastReview key={broadcast.id+':'+broadcast.revision} b={broadcast} state={state} connection={connection} busy={busy} run={run} close={()=>setReview(null)} duplicate={()=>{setReview(null);setComposer({...broadcast,id:'',status:'draft',targets:[],approval:undefined,subject:`Copy of ${broadcast.subject}`});}}/>}
 </>;
}
function BroadcastReview({b,state,connection,busy,run,close,duplicate}:{b:Broadcast;state:CommunicationsState;connection:DeliveryConnection|null;busy:boolean;run:Props['run'];close:()=>void;duplicate:()=>void}){
 const targets=b.status==='draft'?audience(state,b).filter(t=>!state.people.find(p=>p.id===t.personId)?.sample):b.targets;
 const ready=connection?.[b.channel],later=b.scheduledAt>new Date().toISOString();
 return <Dialog open onOpenChange={v=>!v&&close()}><DialogContent className="sm:max-w-[740px]"><DialogHeader><DialogTitle>{b.subject}</DialogTitle><DialogDescription>{b.channel==='email'?'Email from info@1ag.tv':'Text message'} · {later?date(b.scheduledAt):'Next available sending time'} · {broadcastStatus(b)}</DialogDescription></DialogHeader>{b.design?<iframe title="Broadcast email preview" sandbox="" srcDoc={renderEmail(b.design).html} className="email-review-frame"/>:<div className="broadcast-preview whitespace-pre-wrap">{b.body}</div>}{b.channel==='email'&&<p className="text-xs muted">Reply to info@1ag.tv · Unsubscribe link included in the delivered email.</p>}<details className="recipient-review"><summary>{targets.length} recipients · Review audience and delivery details</summary><div className="max-h-60 overflow-auto mt-3">{targets.map(t=><div key={t.personId} className="recipient-row"><span>{state.people.find(p=>p.id===t.personId)?.name??'Removed contact'}<small>{t.destination}</small></span><span>{b.status==='draft'?'Eligible':t.status}<small>{t.reason}</small></span></div>)}</div></details>{b.status==='draft'&&!ready&&<div role="status" className="soft-banner"><AlertCircle size={18}/>{!connection?'Delivery connection has not been verified.':b.channel==='email'?'Amazon SES must be connected before this email can be scheduled or sent.':'Text delivery is not connected.'}</div>}{state.settings.paused&&<p className="text-sm text-amber-800">Workflows are paused. Queued messages will wait until you resume.</p>}<DialogFooter className="flex-wrap"><Button variant="outline" onClick={duplicate}><Copy size={15}/>Duplicate</Button>{b.status!=='cancelled'&&<Button variant="outline" disabled={busy} onClick={async()=>{if(await run({type:'broadcast.cancel',id:b.id}))close();}}>Cancel broadcast</Button>}{b.status==='draft'&&<Button disabled={busy||!ready||!targets.length} onClick={async()=>{if(await run({type:'broadcast.approve',id:b.id,revision:b.revision,audience:targets.map(t=>[t.personId,t.destination,t.context])}))close();}}><Check size={16}/>{later?'Approve & schedule':'Approve & send'}</Button>}</DialogFooter></DialogContent></Dialog>;
}
