import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { State } from '@/lib/pastoral/model';
type Requester=(path:string,init?:RequestInit)=>Promise<Response>;
export function WorkspaceTools({state,version,request,refresh,standalone}:{state:State;version:number;request:Requester;refresh:()=>Promise<void>;standalone:boolean}) {
 const [backup,setBackup]=useState<{format:string;state:State}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 function download(){const href=URL.createObjectURL(new Blob([JSON.stringify({format:'pastoralos-workspace-v1',exportedAt:new Date().toISOString(),version,state})],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download='PastoralOS-Workspace.json';a.click();URL.revokeObjectURL(href);}
 async function restore(){if(!backup)return;setBusy(true);setError('');try{const r=await request('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version,backup})});const d=await r.json();if(!r.ok)throw Error(d.error);setBackup(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to import.');}finally{setBusy(false);}}
 return <section className="panel p-6 mb-6 max-w-4xl"><h2>Workspace backup & transfer</h2><p className="text-sm muted my-3">Download all people, prayer requests, rules, and history. Keep this file private.</p><Button variant="outline" onClick={download}>Download workspace backup</Button>{standalone&&state.people.length===0&&state.prayers.length===0&&state.messages.length===0&&<div className="mt-5 space-y-3"><label className="field"><span>Import a backup from the previous portal</span><Input type="file" accept=".json,application/json" onChange={async e=>{setBackup(null);setError('');const f=e.target.files?.[0];if(!f)return;try{if(f.size>1900000)throw Error('This file is too large.');const d=JSON.parse(await f.text());if(d.format!=='pastoralos-workspace-v1'||!Array.isArray(d.state?.people)||!Array.isArray(d.state?.prayers))throw Error('Choose a PastoralOS workspace backup.');setBackup(d);}catch(e){setError(e instanceof Error?e.message:'Unable to read the backup.');}}}/></label>{backup&&<div className="callout"><p>{backup.state.people.length} people · {backup.state.prayers.length} prayer requests.</p><p className="text-sm my-3">This fills the empty workspace. Sending stays paused and saved messages require fresh approval.</p><Button disabled={busy} onClick={restore}>{busy?'Importing…':'Import workspace'}</Button></div>}</div>}{error&&<p role="alert" className="text-red-700 mt-3">{error}</p>}</section>;
}
export function TwilioTools({request}:{request:Requester}) {
 const [result,setResult]=useState<{configured:boolean;connected:boolean;phone:string;detail:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function check(connect=false){setBusy(true);setError('');try{const r=await request(connect?'/api/twilio/connect':'/api/twilio',{method:connect?'POST':'GET'});const d=await r.json();if(!r.ok)throw Error(d.error);setResult(d);}catch(e){setError(e instanceof Error?e.message:'Unable to check the connection.');}finally{setBusy(false);}}
 return <section className="panel p-6 mb-6 max-w-4xl"><h2>Twilio prayer line</h2><p className="text-sm muted my-3">Check the church number and connect incoming texts. This does not send messages or enable call recording.</p><Button variant="outline" disabled={busy} onClick={()=>check()}>{busy?'Checking…':'Check Twilio connection'}</Button>{result&&<div className="callout mt-4"><h3>{result.phone} · {result.connected?'Incoming texts connected':result.configured?'Ready to connect':'Setup needed'}</h3><p className="text-sm mt-2">{result.detail}</p>{!result.configured&&<a className="link-button mt-3 inline-block" href="https://supabase.com/dashboard/project/mewbiwkdstngmbeispwo/functions/secrets" target="_blank" rel="noreferrer">Open secure connection settings</a>}{result.configured&&!result.connected&&<Button disabled={busy} className="mt-3" onClick={()=>check(true)}>Connect incoming texts</Button>}</div>}{error&&<p role="alert" className="text-red-700 mt-3">{error}</p>}</section>;
}
