'use client';
import {useEffect,useState} from 'react';
import {Plus,HeartHandshake,Bell,Check,Clock,PenLine,ArrowRight,AlertCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {careData,centralDay,careLocalTime,careInputTime,quickNoteSuggestion,type CareCase,type CareTask,type CareSource,type CarePlan} from '@/lib/pastoral/pastoral-care';
import {servingData,servingKey,servingInstant} from '@/lib/pastoral/serving';
import {smsThreads} from '@/lib/pastoral/sms-conversations';
import {prayerNeedsApproval} from '@/lib/pastoral/prayer-approval';
import type {State,Action} from '@/lib/pastoral/model';
import type {CommunicationsState,DeliveryConnection} from '@/lib/pastoral/communications';
import './pastoral-care.css';

type Props={state:State;busy:boolean;run:(a:Action)=>Promise<boolean>};
type CareLaunch={mode:'case'|'note'|'task';personId?:string;source?:CareSource;caseId?:string};
export const openCare=(detail:CareLaunch)=>window.dispatchEvent(new CustomEvent('pastoral-care-open',{detail}));
const stamp=(s:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(s));
const nextTime=()=>careInputTime(new Date(Date.now()+86400000).toISOString());
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
export function CarePersonPicker({state,value,onChange}:{state:State;value:string;onChange:(id:string)=>void}){
 const [query,setQuery]=useState('');const selected=state.people.find(p=>p.id===value);
 return <div className="field"><label htmlFor="care-person-search">Person</label>{selected?<div className="care-selected"><strong>{selected.name}</strong><Button type="button" size="sm" variant="ghost" onClick={()=>onChange('')}>Change</Button></div>:<><Input id="care-person-search" aria-label="Find person for care" placeholder="Start typing a name…" autoComplete="off" value={query} onChange={e=>setQuery(e.target.value)}/>{query.trim()&&<div className="care-person-results">{state.people.filter(p=>!p.archived&&p.name.toLowerCase().includes(query.toLowerCase())).slice(0,8).map(p=><button type="button" key={p.id} onClick={()=>{onChange(p.id);setQuery('');}}>{p.name}</button>)}</div>}</>}</div>;
}
export function CareDialogs(props:Props){
 const [launch,setLaunch]=useState<CareLaunch|null>(null);
 useEffect(()=>{const handler=(e:Event)=>setLaunch((e as CustomEvent<CareLaunch>).detail);window.addEventListener('pastoral-care-open',handler);return()=>window.removeEventListener('pastoral-care-open',handler);},[]);
 if(!launch)return null;
 return <Dialog open onOpenChange={v=>!v&&setLaunch(null)}><DialogContent className="sm:max-w-[700px]"><DialogHeader><DialogTitle>{launch.mode==='case'?'Start a care plan':launch.mode==='note'?'Quick note':'Add a follow-up'}</DialogTitle><DialogDescription>Private to your PastoralOS account. Uses your existing People records. Dates are Central time.</DialogDescription></DialogHeader><CareEntry key={JSON.stringify(launch)} {...props} launch={launch} close={()=>setLaunch(null)}/></DialogContent></Dialog>;
}
function CareEntry({state,busy,run,launch,close}:Props&{launch:CareLaunch;close:()=>void}){
 const [personId,setPerson]=useState(launch.personId??''),[title,setTitle]=useState(''),[detail,setDetail]=useState(''),[kind,setKind]=useState('note'),[due,setDue]=useState(nextTime()),[follow,setFollow]=useState(false),[repeat,setRepeat]=useState(0),[notify,setNotify]=useState(true),[plan,setPlan]=useState(''),[anchor,setAnchor]=useState(centralDay(new Date())),[steps,setSteps]=useState([{title:'Personal follow-up',dueAt:nextTime()}]),[error,setError]=useState('');
 const source=launch.source?.kind==='prayer'?state.prayers.find(p=>p.id===launch.source?.id)?.original:state.inbox.find(i=>i.id===launch.source?.id)?.body;
 function usePlan(id:string){setPlan(id);const p=careData(state).plans.find(x=>x.id===id);if(!p)return;setTitle(p.name);setSteps(p.steps.map(step=>{const d=new Date(anchor+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+step.days);return {title:step.title,dueAt:d.toISOString().slice(0,10)+'T09:00'};}));}
 return <form className="care-form" onSubmit={async e=>{e.preventDefault();setError('');try{let action:Action;
  if(launch.mode==='case')action={type:'care.case.save',personId,title,detail,source:launch.source,steps:steps.map(s=>({title:s.title,dueAt:careLocalTime(s.dueAt)}))};
  else if(launch.mode==='note')action={type:'care.note.add',personId,body:detail,kind,caseId:launch.caseId,...(follow?{followUpAt:careLocalTime(due),followUpTitle:title||'Personal follow-up'}:{})};
  else action={type:'care.task.save',personId,caseId:launch.caseId,title,dueAt:careLocalTime(due),repeatDays:repeat,notify};
  if(await run(action))close();}catch(err){setError(err instanceof Error?err.message:'Check the dates.');}}}>
  <CarePersonPicker state={state} value={personId} onChange={setPerson}/>
  {source&&<details className="care-source"><summary>Original {launch.source?.kind==='prayer'?'prayer request':'conversation'}</summary><p className="whitespace-pre-wrap">{source}</p><small>Creating care does not approve or share this message.</small></details>}
  {launch.mode==='case'&&<><div className="care-two"><Field label="Start with a plan"><select className="plain-select" value={plan} onChange={e=>usePlan(e.target.value)}><option value="">Make my own plan</option>{careData(state).plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Event date for plan"><Input type="date" aria-label="Care event date" value={anchor} onChange={e=>{setAnchor(e.target.value);setPlan('');}}/></Field></div><Field label="Care need"><Input aria-label="Care need" required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Recovery after surgery"/></Field><Field label="Private details"><Textarea aria-label="Care details" rows={3} maxLength={6000} value={detail} onChange={e=>setDetail(e.target.value)}/></Field><h3>Next actions</h3><p className="text-sm muted">Review each date before saving. Past dates appear as overdue.</p>{steps.map((s,i)=><div className="care-step" key={i}><Input aria-label={`Action ${i+1}`} required value={s.title} onChange={e=>setSteps(steps.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><Input aria-label={`Action ${i+1} time`} required type="datetime-local" value={s.dueAt} onChange={e=>setSteps(steps.map((x,n)=>n===i?{...x,dueAt:e.target.value}:x))}/><Button type="button" variant="ghost" disabled={steps.length===1} onClick={()=>setSteps(steps.filter((_,n)=>n!==i))}>Remove</Button></div>)}<Button type="button" variant="outline" disabled={steps.length>=20} onClick={()=>setSteps([...steps,{title:'Follow up',dueAt:nextTime()}])}><Plus size={15}/>Add action</Button></>}
  {launch.mode==='note'&&<><Field label="What happened?"><select className="plain-select" value={kind} onChange={e=>setKind(e.target.value)}><option value="note">Note</option><option value="visit">Visit</option><option value="call">Phone call</option></select></Field><Field label="Your note"><Textarea aria-label="Quick note" required rows={4} maxLength={6000} value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Visited today. Call again Friday…"/></Field><p className="text-xs muted">You can use your phone or computer keyboard’s dictation to enter a note.</p><Button type="button" variant="outline" disabled={!detail.trim()} onClick={()=>{const suggestion=quickNoteSuggestion(detail);setTitle(suggestion.title);setFollow(true);if(suggestion.dueAt)setDue(careInputTime(suggestion.dueAt));}}>Prepare a follow-up from this note</Button><label className="check-row"><input type="checkbox" checked={follow} onChange={e=>setFollow(e.target.checked)}/>Add a follow-up</label>{follow&&<p className="soft-banner">Review the action and date below. Suggestions are never scheduled until you save.</p>}</>}
  {(launch.mode==='task'||launch.mode==='note'&&follow)&&<><Field label="Next action"><Input aria-label="Follow-up action" required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="When · Central"><Input aria-label="Follow-up time" required type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></Field>{launch.mode==='task'&&<><Field label="Repeat after completion"><select className="plain-select" value={repeat} onChange={e=>setRepeat(Number(e.target.value))}><option value={0}>One time</option><option value={7}>Every week</option><option value={14}>Every two weeks</option><option value={30}>Every 30 days</option></select></Field><label className="check-row"><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/>Send a reminder using my Settings</label></>}</>}
  {error&&<p role="alert" className="care-error">{error}</p>}<div className="care-actions"><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={busy||!personId}>{launch.mode==='case'?'Save care plan':launch.mode==='note'?'Save note':'Save follow-up'}</Button></div>
 </form>;
}
export function CareTaskCard({state,busy,run,task}:Props&{task:CareTask}){
 const [edit,setEdit]=useState<'done'|'snooze'|'edit'|null>(null),[when,setWhen]=useState(careInputTime(task.dueAt)),[title,setTitle]=useState(task.title),[note,setNote]=useState(''),[next,setNext]=useState(''),[error,setError]=useState('');
 const person=state.people.find(p=>p.id===task.personId),overdue=task.status==='open'&&new Date(task.dueAt)<new Date();
 return <article className="care-task"><div><span className={`badge ${overdue?'amber':'gray'}`}>{task.status==='open'?(overdue?'Overdue':'Upcoming'):task.status}</span><h3>{task.title}</h3><p>{person?.name??'Former contact'} · {stamp(task.dueAt)} CT</p></div>{task.status==='open'&&<div className="care-actions"><Button size="sm" disabled={busy} onClick={()=>{setEdit('done');setError('');}}><Check size={14}/>Done</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>{setWhen(nextTime());setEdit('snooze');setError('');}}><Clock size={14}/>Later</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>{setWhen(careInputTime(task.dueAt));setEdit('edit');setError('');}}>Edit</Button></div>}
 {edit&&<Dialog open onOpenChange={v=>!v&&setEdit(null)}><DialogContent><DialogHeader><DialogTitle>{edit==='done'?'Complete follow-up':edit==='snooze'?'Remind me later':'Edit follow-up'}</DialogTitle><DialogDescription>{task.title} · {person?.name}. All dates are Central time.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setError('');try{const action:Action=edit==='done'?{type:'care.task.done',id:task.id,note,...(next?{nextDueAt:careLocalTime(next)}:{})}:edit==='snooze'?{type:'care.task.snooze',id:task.id,dueAt:careLocalTime(when)}:{type:'care.task.save',id:task.id,personId:task.personId,caseId:task.caseId,title,dueAt:careLocalTime(when),notify:task.notify,repeatDays:task.repeatDays};if(await run(action))setEdit(null);}catch(err){setError(err instanceof Error?err.message:'Check the date.');}}}>
 {edit==='done'?<><Field label="What happened? (optional)"><Textarea aria-label="Completion note" value={note} onChange={e=>setNote(e.target.value)}/></Field><Field label={task.repeatDays?`Next follow-up (otherwise repeats in ${task.repeatDays} days)`:'Next follow-up (optional)'}><Input aria-label="Next follow-up time" type="datetime-local" value={next} onChange={e=>setNext(e.target.value)}/></Field></>:<>{edit==='edit'&&<Field label="Action"><Input aria-label="Edit follow-up title" required value={title} onChange={e=>setTitle(e.target.value)}/></Field>}<Field label="When · Central"><Input aria-label="Reschedule follow-up" type="datetime-local" required value={when} onChange={e=>setWhen(e.target.value)}/></Field></>}{error&&<p role="alert" className="care-error">{error}</p>}<div className="care-actions">{edit==='edit'&&<Button type="button" variant="ghost" disabled={busy} onClick={async()=>{if(await run({type:'care.task.cancel',id:task.id}))setEdit(null);}}>Cancel follow-up</Button>}<Button disabled={busy}>Save</Button></div></form></DialogContent></Dialog>}
 </article>;
}
export function CarePanel(props:Props){
 const {state,busy,run}=props,c=careData(state);const [filter,setFilter]=useState('open'),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[templates,setTemplates]=useState(false);
 const cases=c.cases.filter(x=>(filter==='all'||x.status===filter)&&`${x.title} ${state.people.find(p=>p.id===x.personId)?.name}`.toLowerCase().includes(query.toLowerCase())),item=c.cases.find(x=>x.id===selected);
 return <div className="care-root"><div className="care-toolbar"><Input aria-label="Search care" placeholder="Search people or care needs…" value={query} onChange={e=>setQuery(e.target.value)}/><select className="plain-select" aria-label="Care status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open</option><option value="waiting">Waiting</option><option value="closed">Completed</option><option value="all">All care</option></select><Button variant="outline" onClick={()=>setTemplates(!templates)}>Care plans</Button><Button onClick={()=>openCare({mode:'case'})}><Plus size={16}/>New care need</Button></div>{templates&&<CarePlans {...props}/>}<div className="care-layout"><section className="care-case-list">{cases.length?cases.map(x=><button className={`panel care-case ${x.id===selected?'selected':''}`} key={x.id} onClick={()=>setSelected(x.id)}><span className="badge">{x.status}</span><h3>{x.title}</h3><p>{state.people.find(p=>p.id===x.personId)?.name}</p><small>{c.tasks.filter(t=>t.caseId===x.id&&t.status==='open').length} next actions</small></button>):<div className="panel p-7"><HeartHandshake size={28}/><h3 className="mt-3">A place to keep track of care</h3><p className="muted mt-2">Start with a person, a need, and the next action. You can also create care from a prayer request or conversation.</p></div>}</section><section>{item?<CareDetail key={item.id} {...props} item={item}/>:<div className="panel p-7"><h2>Personal follow-ups</h2><p className="muted mt-2 mb-4">Select a care need, or manage your individual reminders here.</p><Button variant="outline" onClick={()=>openCare({mode:'task'})}>Add a follow-up</Button>{c.tasks.filter(t=>!t.caseId&&t.status==='open').sort((a,b)=>a.dueAt.localeCompare(b.dueAt)).map(t=><CareTaskCard key={t.id} {...props} task={t}/>)}</div>}</section></div></div>;
}
function CareDetail({item,...props}:Props&{item:CareCase}){
 const {state,busy,run}=props,[editing,setEditing]=useState(false),[title,setTitle]=useState(item.title),[detail,setDetail]=useState(item.detail),[closing,setClosing]=useState(false),c=careData(state);
 return <div className="panel care-detail"><div className="care-toolbar"><div><h2>{item.title}</h2><p className="muted">{state.people.find(p=>p.id===item.personId)?.name}</p></div><Button variant="ghost" onClick={()=>setEditing(!editing)}><PenLine size={15}/>Edit</Button></div>{editing?<form onSubmit={async e=>{e.preventDefault();if(await run({type:'care.case.save',id:item.id,personId:item.personId,title,detail}))setEditing(false);}}><Field label="Care need"><Input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Private details"><Textarea value={detail} onChange={e=>setDetail(e.target.value)}/></Field><Button disabled={busy}>Save details</Button></form>:<p className="whitespace-pre-wrap mb-4">{item.detail||'No additional details recorded.'}</p>}{item.source&&<p className="text-xs muted mb-4">Linked to {item.source.kind==='prayer'?'a prayer request':'a conversation'}. Prayer approval and care completion remain separate.</p>}<div className="care-actions"><Button variant="outline" onClick={()=>openCare({mode:'note',personId:item.personId,caseId:item.id})}>Record a call or visit</Button>{item.status!=='closed'&&<Button variant="outline" onClick={()=>openCare({mode:'task',personId:item.personId,caseId:item.id})}>Add follow-up</Button>}<Button variant="ghost" disabled={busy} onClick={()=>void run({type:'care.case.status',id:item.id,status:item.status==='waiting'?'open':'waiting'})}>{item.status==='waiting'?'Resume care':'Waiting'}</Button><Button variant="ghost" disabled={busy} onClick={()=>item.status==='closed'?void run({type:'care.case.status',id:item.id,status:'open'}):setClosing(true)}>{item.status==='closed'?'Reopen':'Complete care'}</Button></div>{c.tasks.filter(t=>t.caseId===item.id).sort((a,b)=>a.dueAt.localeCompare(b.dueAt)).map(t=><CareTaskCard key={t.id+':'+t.revision} {...props} task={t}/>)}<h3 className="mt-6 mb-3">Care history</h3>{c.notes.filter(n=>n.caseId===item.id).map(n=><div className="timeline-item" key={n.id}><p className="whitespace-pre-wrap">{n.body}</p><small className="muted">{stamp(n.at)} CT · {n.kind}</small></div>)}{closing&&<Dialog open onOpenChange={setClosing}><DialogContent><DialogHeader><DialogTitle>Complete this care need?</DialogTitle><DialogDescription>Any remaining follow-ups for this care need will be cancelled. Notes and completed actions stay in the history.</DialogDescription></DialogHeader><div className="care-actions"><Button variant="outline" onClick={()=>setClosing(false)}>Keep open</Button><Button disabled={busy} onClick={async()=>{if(await run({type:'care.case.status',id:item.id,status:'closed'}))setClosing(false);}}>Complete care</Button></div></DialogContent></Dialog>}</div>;
}
function CarePlans({state,busy,run}:Props){
 const [id,setId]=useState(careData(state).plans[0]?.id??''),[name,setName]=useState(careData(state).plans[0]?.name??''),[steps,setSteps]=useState<CarePlan['steps']>(careData(state).plans[0]?.steps??[]);
 return <details open className="panel p-6 mb-5"><summary className="font-semibold">Reusable care plans</summary><p className="text-sm muted my-3">Edit the starting actions once. Changes affect new care plans only. Negative days are before the event date.</p><form onSubmit={async e=>{e.preventDefault();await run({type:'care.plan.save',id:id||undefined,name,steps});}}><select aria-label="Care plan template" className="plain-select mb-4" value={id} onChange={e=>{setId(e.target.value);const p=careData(state).plans.find(x=>x.id===e.target.value);setName(p?.name??'');setSteps(p?.steps??[{title:'Follow up',days:0}]);}}><option value="">Create a new plan</option>{careData(state).plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Field label="Plan name"><Input required value={name} onChange={e=>setName(e.target.value)}/></Field>{steps.map((s,i)=><div className="care-step" key={i}><Input aria-label={`Plan step ${i+1}`} required value={s.title} onChange={e=>setSteps(steps.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><Input aria-label={`Plan day ${i+1}`} required type="number" min={-365} max={730} value={s.days} onChange={e=>setSteps(steps.map((x,n)=>n===i?{...x,days:Number(e.target.value)}:x))}/><Button type="button" variant="ghost" onClick={()=>setSteps(steps.filter((_,n)=>n!==i))}>Remove</Button></div>)}<div className="care-actions"><Button type="button" variant="outline" onClick={()=>setSteps([...steps,{title:'Follow up',days:7}])}>Add step</Button><Button disabled={busy||!steps.length}>Save plan</Button></div></form></details>;
}
export function TodayAgenda({onNavigate,...props}:Props&{onNavigate:(view:'care'|'prayer'|'communications'|'serving'|'guests'|'settings')=>void}){
 const {state}=props,c=careData(state),today=centralDay(new Date()),[filter,setFilter]=useState('today');
 const tasks=c.tasks.filter(t=>t.status==='open'&&state.people.some(p=>p.id===t.personId&&!p.archived)).sort((a,b)=>a.dueAt.localeCompare(b.dueAt));
 const shown=tasks.filter(t=>filter==='all'||(filter==='overdue'?new Date(t.dueAt)<new Date():centralDay(new Date(t.dueAt))<=today));
 const prayers=state.prayers.filter(p=>prayerNeedsApproval(state,p.id)).length,conversations=smsThreads(state as CommunicationsState).filter(t=>!t.done&&t.messages.at(-1)?.direction==='in').length;
 const upcoming=servingData(state).services.filter(s=>!s.cancelled&&servingInstant(s.date,s.time)>new Date()).sort((a,b)=>a.date.localeCompare(b.date));
 const next=upcoming[0],unconfirmed=next?.areas.reduce((sum,a)=>sum+a.personIds.filter(id=>servingData(state).responses?.[servingKey(next.id,a.id,id)]?.status!=='confirmed').length,0)??0;
 return <div className="care-agenda"><div className="care-summary-grid">{[{title:'Prayer requests',count:prayers,view:'prayer' as const,detail:'Awaiting your decision'},{title:'Conversations',count:conversations,view:'communications' as const,detail:'Latest message needs a reply'},{title:'Guest replies',count:Object.keys(c.replyHolds).length,view:'guests' as const,detail:'Follow-up paused for attention'},{title:'Serving confirmations',count:unconfirmed,view:'serving' as const,detail:next?next.title+' · '+next.date:'No upcoming service'}].map(x=><button className="panel care-summary" key={x.title} onClick={()=>onNavigate(x.view)}><span>{x.title}</span><strong>{x.count}</strong><small>{x.detail}</small></button>)}</div><section className="panel p-6"><div className="care-toolbar"><div><h2>Your next actions</h2><p className="muted text-sm">Calls, visits, and follow-ups in one place.</p></div><Button variant="outline" onClick={()=>openCare({mode:'task'})}><Plus size={15}/>Follow-up</Button><Button onClick={()=>openCare({mode:'note'})}><PenLine size={15}/>Quick note</Button></div><div className="care-filter">{[['today','Today'],['overdue','Overdue'],['all','Upcoming']].map(([id,label])=><button aria-pressed={filter===id} key={id} onClick={()=>setFilter(id)}>{label}</button>)}</div>{shown.length?shown.map(t=><CareTaskCard {...props} key={t.id+':'+t.revision} task={t}/>):<div className="care-empty"><Check size={25}/><h3>No follow-ups in this view</h3><p>Add a care need or a personal reminder to start planning your day.</p></div>}<Button variant="ghost" onClick={()=>onNavigate('care')}>Open pastoral care<ArrowRight size={15}/></Button></section>{c.preferences.channel==='off'&&<p className="soft-banner mt-4"><Bell size={18}/><span>Personal reminders currently stay inside the app. Choose when and how to receive them in Settings.</span><button className="link-button" onClick={()=>onNavigate('settings')}>Settings</button></p>}</div>;
}
function personActivity(state:State,personId:string){
 const care=careData(state),events=care.notes.filter(n=>n.personId===personId).map(n=>({id:n.id,at:n.at,body:n.body,kind:n.kind as string}));
 for(const i of state.inbox.filter(i=>i.personId===personId))events.push({id:'in:'+i.id,at:i.at,body:i.body,kind:i.source==='twilio'?'Received text':'Conversation note'});
 for(const b of (state as CommunicationsState).broadcasts??[])for(const target of b.targets.filter(t=>t.personId===personId&&t.attemptedAt))events.push({id:'out:'+b.id+':'+personId,at:target.attemptedAt!,body:b.subject+' — '+b.body,kind:(b.channel==='sms'?'Text':'Email')+' · '+target.status});
 for(const v of state.visits??[])if(v.personId===personId)events.push({id:'visit:'+v.at,at:v.at,body:'Church visit recorded',kind:'Attendance'});
 return events.sort((a,b)=>b.at.localeCompare(a.at)).slice(0,40);
}
export function PersonCare({personId,...props}:Props&{personId:string}){
 const {state,busy,run}=props,c=careData(state),availability=c.availability.find(x=>x.personId===personId),[from,setFrom]=useState(availability?.from??centralDay(new Date())),[through,setThrough]=useState(availability?.through??centralDay(new Date()));
 return <section className="mt-6 border-t pt-5"><h3>Care and follow-through</h3><div className="care-actions my-3"><Button variant="outline" onClick={()=>openCare({mode:'case',personId})}>Start care</Button><Button variant="outline" onClick={()=>openCare({mode:'note',personId})}>Quick note</Button></div>{c.replyHolds[personId]&&<div className="soft-banner my-3"><span>Guest follow-up paused after a reply.</span><Button variant="outline" disabled={busy} onClick={()=>run({type:'care.reply.resume',personId})}>Resume follow-up</Button></div>}{c.tasks.filter(t=>t.personId===personId&&t.status==='open').map(t=><CareTaskCard {...props} key={t.id+':'+t.revision} task={t}/>)}<details className="my-5"><summary>Serving availability</summary><p className="text-xs muted my-2">Mark a temporary absence. Only availability is shown on serving schedules.</p>{availability&&<p className="badge amber">Unavailable {availability.from} through {availability.through}</p>}<div className="care-two my-3"><Field label="From"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Through"><Input type="date" value={through} onChange={e=>setThrough(e.target.value)}/></Field></div><div className="care-actions"><Button size="sm" disabled={busy} onClick={()=>run({type:'care.availability',personId,from,through})}>Save unavailable dates</Button>{availability&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>run({type:'care.availability',personId,clear:true})}>Clear absence</Button>}</div></details><h3 className="mb-3">Recent activity</h3><p className="text-xs muted mb-3">Care notes, received messages, communication attempts, and recorded visits.</p>{personActivity(state,personId).map(n=><div className="timeline-item" key={n.id}><p className="whitespace-pre-wrap">{n.body}</p><small className="muted">{stamp(n.at)} CT · {n.kind}</small></div>)}</section>;
}
export function ReminderSettings({request,...props}:Props&{request:(path:string,init?:RequestInit)=>Promise<Response>}){
 const {state,busy,run}=props,c=careData(state),[channel,setChannel]=useState(c.preferences.channel),[time,setTime]=useState(c.preferences.digestTime),[due,setDue]=useState(c.preferences.dueReminders),[pause,setPause]=useState(c.preferences.pauseOnReply),[connection,setConnection]=useState<DeliveryConnection|null>(null);
 useEffect(()=>{let active=true;request('/api/delivery-connection').then(r=>r.ok?r.json():null).then(x=>{if(active)setConnection(x);}).catch(()=>{});return()=>{active=false;};},[request]);
 return <section className="panel p-6 mb-6"><h2>Your personal reminders</h2><p className="text-sm muted mt-2 mb-5">Choose when and how PastoralOS reminds you. Messages contain counts and a private link, not confidential care details.</p><form onSubmit={async e=>{e.preventDefault();await run({type:'care.preferences',preferences:{channel,digestTime:time,dueReminders:due,pauseOnReply:pause}});}}><div className="care-two"><Field label="Delivery method"><select className="plain-select" aria-label="Personal reminder delivery" value={channel} onChange={e=>setChannel(e.target.value as typeof channel)}><option value="off">Inside the app only</option><option value="email">Email my signed-in staff address</option><option value="sms">Text my pastor notification number</option></select></Field><Field label="Morning summary · Central"><Input aria-label="Morning summary time" type="time" required value={time} onChange={e=>setTime(e.target.value)}/></Field></div><label className="check-row"><input type="checkbox" checked={due} onChange={e=>setDue(e.target.checked)}/>Also remind me when a follow-up becomes due</label><label className="check-row"><input type="checkbox" checked={pause} onChange={e=>setPause(e.target.checked)}/>Pause a guest’s automated follow-up when they reply</label><p className="text-xs muted mb-4">Email goes to the account saving these preferences. Texts use your pastor notification number in Access &amp; history. Due reminders follow church sending hours. The daily summary uses your chosen time. Global Pause workflows pauses personal reminders too.</p>{channel!=='off'&&connection&&!connection[channel==='email'?'email':'sms']&&<p className="soft-banner mb-4">{channel==='sms'?connection.smsReason:connection.emailReason}</p>}<Button disabled={busy}>Save reminder preferences</Button></form><details className="mt-5"><summary>Reminder delivery history</summary><p className="text-xs muted my-3">Accepted by provider does not mean read. Unknown delivery outcomes are not retried automatically.</p>{c.notices.length?c.notices.slice().reverse().slice(0,30).map(n=><div className="care-delivery" key={n.id}><div><strong>{n.kind==='digest'?'Daily summary':'Follow-up reminder'} · {n.status}</strong><p>{stamp(n.createdAt)} CT · {n.channel}</p><small>{n.reason}</small></div>{n.status==='failed'&&n.day===centralDay(new Date())&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>run({type:'care.notice.retry',id:n.id})}>Retry failed reminder</Button>}</div>):<p>No reminders sent yet.</p>}</details></section>;
}
export function CareHealth({state,request}:{state:State;request:(path:string,init?:RequestInit)=>Promise<Response>}){
 const [health,setHealth]=useState<{lastCompletedAt?:string;lastError?:string}|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;const check=()=>request('/api/health').then(async r=>{if(!r.ok)throw Error();const data=await r.json();if(active){setHealth(data);setFailed(false);}}).catch(()=>{if(active)setFailed(true);});void check();const timer=setInterval(check,60000);return()=>{active=false;clearInterval(timer);};},[request]);
 const notices=careData(state).notices.filter(n=>['failed','uncertain'].includes(n.status)||n.status==='pending'&&n.reason),stale=!!health&&(!health.lastCompletedAt||Date.now()-Date.parse(health.lastCompletedAt)>10*60000),issues=careData(state).worker?.issues??[],deliveryIssues=((state as CommunicationsState).broadcasts??[]).reduce((count,b)=>count+b.targets.filter(t=>['failed','uncertain'].includes(t.status)&&Date.now()-Date.parse(t.attemptedAt??b.createdAt)<7*86400000).length,0)+state.deliveries.filter(d=>['failed','uncertain'].includes(d.status)&&Date.now()-Date.parse(d.attemptedAt??d.at)<7*86400000).length;
 if(!failed&&!stale&&!health?.lastError&&!notices.length&&!issues.length&&!deliveryIssues)return <p className="care-health-ok"><Check size={14}/>{health?'Background scheduling checked '+(health.lastCompletedAt?stamp(health.lastCompletedAt)+' CT':'recently'):'Checking background scheduling…'}</p>;
 return <div className="soft-banner !bg-amber-50 mb-5" role="status"><AlertCircle size={19}/><div><strong>Delivery needs attention</strong><p>{failed?'Could not check background scheduling. ':stale?'The background scheduler has not completed recently. ':''}{health?.lastError?'A background job reported an error. ':''}{notices.length?`${notices.length} personal reminders need attention. Check reminder delivery in Settings. `:''}{issues.join(' · ')}{deliveryIssues?` ${deliveryIssues} recent text or email delivery attempts need review in Communications or guest follow-up.`:''}</p><small>Open follow-ups remain on Today. Do not assume a reminder was delivered.</small></div></div>;
}
