'use client';
import {useState,type ReactNode} from 'react';
import {Search,Plus,Mail,Phone,Pencil,X,Check,Users,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {directoryGroups,memberships,preferences,type CommunicationsState,type DirectoryPerson,type ContactPreference} from '@/lib/pastoral/communications';
import {isAssimilating,type Action,type Person} from '@/lib/pastoral/model';
type Props={state:CommunicationsState;busy:boolean;run:(a:Action)=>Promise<boolean>;refresh:()=>Promise<void>;edit:(p:Person)=>void;details:(p:Person)=>void;importTools:ReactNode};
const initials=(name:string)=>name.split(' ').map(s=>s[0]).slice(0,2).join('');
function exportPeople(state:CommunicationsState){const groups=directoryGroups(state),cell=(v:string)=>'"'+v.replace(/^[=+\-@]/,"'").replaceAll('"','""')+'"';const rows=state.people.filter(p=>!p.archived).map(p=>[p.name,p.email,p.phone,isAssimilating(p)?p.stage:'Not enrolled',memberships(p).map(id=>groups.find(g=>g.id===id)?.name??id).join('; ')]);const csv=[['Name','Email','Phone','Assimilation','Tags'],...rows].map(row=>row.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='PastoralOS-People.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function PeopleDirectory({state,busy,run,refresh,edit,details,importTools}:Props){
 const [tab,setTab]=useState('Everyone'),[search,setSearch]=useState(''),[tag,setTag]=useState('all'),[selected,setSelected]=useState<string|null>(null),[manage,setManage]=useState(false),[name,setName]=useState(''),[membershipEdit,setMembershipEdit]=useState(false),[archived,setArchived]=useState(false);
 const groups=directoryGroups(state),person=state.people.find(p=>p.id===selected) as DirectoryPerson|undefined;
 const people=state.people.filter(p=>p.archived===archived&&(tag==='all'||memberships(p).includes(tag))&&`${p.name} ${p.email} ${p.phone}`.toLowerCase().includes(search.toLowerCase()));
 return <div className={`directory-layout ${person?'has-profile':''}`}><section className="directory-main"><div className="section-tabs" role="tablist" aria-label="People views">{['Everyone','Tags'].map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>{setTab(t);void refresh();}}>{t}</button>)}<div className="ml-auto flex gap-2"><Button variant="outline" onClick={()=>setManage(true)}>Manage tags</Button>{importTools}</div></div>
 {tab==='Tags'?<><p className="muted text-sm mb-5">Organize people once. Use these tags throughout PastoralOS and when sending communications.</p><div className="group-grid">{groups.map(g=><button className="group-card" key={g.id} onClick={()=>{setTag(g.id);setTab('Everyone');void refresh();}}><Users size={20}/><h3>{g.name}</h3><p>{state.people.filter(p=>!p.archived&&memberships(p).includes(g.id)).length} people</p></button>)}<button className="group-card" onClick={()=>setManage(true)}><Plus size={20}/><h3>Create a tag</h3><p>Church members, Volunteers…</p></button></div></>:<><div className="directory-filters"><label className="search-input"><Search size={18}/><Input aria-label="Search people" placeholder="Search people…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter by tag" value={tag} onChange={e=>setTag(e.target.value)}><option value="all">All tags</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><div className="directory-table-wrap"><table className="directory-table"><thead><tr><th>Name</th><th>Tags</th><th>Assimilation</th><th><span className="sr-only">Status</span></th></tr></thead><tbody>{people.map((p,i)=><tr key={p.id} className={selected===p.id?'selected':''}><td><button onClick={()=>setSelected(p.id)} className="person-link"><span className={`person-avatar color-${i%4}`}>{initials(p.name)}</span><span>{p.name}<small>{p.email||p.phone||'No contact details'}</small></span></button></td><td><div className="chip-list">{memberships(p).map(id=><span className={`group-chip ${id==='prayer'?'prayer':''}`} key={id}>{groups.find(g=>g.id===id)?.name??id}</span>)}{!memberships(p).length&&<span className="muted">No tags</span>}</div></td><td><span className={`stage-chip ${!isAssimilating(p)?'connected':''}`}>{isAssimilating(p)?p.stage:'Not enrolled'}</span></td><td>{p.paused?<span className="badge amber">Paused</span>:<button aria-label={`Open ${p.name}`} onClick={()=>setSelected(p.id)}>•••</button>}</td></tr>)}</tbody></table></div>{!people.length&&<div className="directory-empty">No people match these filters.</div>}<div className="directory-footer"><Button size="sm" variant="ghost" onClick={()=>exportPeople(state)}><Download size={14}/>Export people</Button><span>{people.length} {people.length===1?'person':'people'}</span><label className="flex items-center gap-2"><Checkbox checked={archived} onCheckedChange={v=>setArchived(v===true)}/>Show archived</label></div></>}
 </section>{person&&<aside className="person-panel" aria-label="Person profile"><button className="profile-close" aria-label="Close profile" onClick={()=>setSelected(null)}><X size={18}/></button><div className="profile-heading"><span className="person-avatar large">{initials(person.name)}</span><div><h2>{person.name}</h2><span className="stage-chip connected">{isAssimilating(person)?person.stage:'Not enrolled'}</span></div><Button variant="ghost" size="sm" aria-label="Edit contact details" onClick={()=>edit(person)}><Pencil size={16}/></Button></div><section><h3>Contact</h3><p><Mail size={17}/>{person.email||'No email recorded'}</p><p><Phone size={17}/>{person.phone||'No phone recorded'}</p></section><section><h3>Tags</h3><div className="chip-list">{memberships(person).map(id=><span key={id} className="group-chip">{groups.find(g=>g.id===id)?.name??id}</span>)}</div><Button variant="outline" size="sm" className="mt-3" onClick={()=>setMembershipEdit(true)}><Plus size={15}/>Edit tags & preferences</Button><Button variant="ghost" size="sm" onClick={()=>setManage(true)}>Create a tag</Button></section><section><h3>Assimilation</h3><label className="flex gap-2 items-center text-sm"><Checkbox disabled={busy||!!person.completedAt} checked={isAssimilating(person)} onCheckedChange={v=>void run({type:'person.enrollment',id:person.id,enroll:v===true})}/>Enroll in assimilation</label><p className="!text-xs muted mt-3">Starts new guest follow-up. Prayer chain and other tags do not enroll someone.</p></section><section><h3>Communication preferences</h3><table className="preference-table"><thead><tr><th>Tag</th><th>Email</th><th>Text</th></tr></thead><tbody>{memberships(person).map(id=><tr key={id}><td>{groups.find(g=>g.id===id)?.name??id}</td>{(['email','sms'] as const).map(c=><td key={c}>{preferences(person,id)[c]?<Check size={17} aria-label="Allowed"/>:'—'}</td>)}</tr>)}</tbody></table></section><section><h3>Notes & activity</h3>{person.note&&<p className="!block whitespace-pre-wrap">{person.note}</p>}<Button variant="outline" size="sm" className="mt-3" onClick={()=>details(person)}>Open history</Button></section></aside>}
 <Dialog open={manage} onOpenChange={setManage}><DialogContent><DialogHeader><DialogTitle>Manage tags</DialogTitle><DialogDescription>Tags are shared across People, Prayer chain, and Communications.</DialogDescription></DialogHeader><div className="chip-list">{groups.map(g=><span className="group-chip" key={g.id}>{g.name}</span>)}</div><label className="field"><span>New tag</span><Input aria-label="Tag name" placeholder="Church members, Volunteers…" maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><DialogFooter><Button disabled={busy||!name.trim()} onClick={async()=>{if(await run({type:'directory.group',name})){setName('');}}}><Plus size={15}/>Create tag</Button><Button variant="outline" onClick={()=>setManage(false)}>Done</Button></DialogFooter></DialogContent></Dialog>
 {person&&membershipEdit&&<MembershipEditor key={person.id} person={person} state={state} busy={busy} run={run} close={()=>setMembershipEdit(false)}/>}
 </div>;
}
function MembershipEditor({person,state,busy,run,close}:{person:DirectoryPerson;state:CommunicationsState;busy:boolean;run:Props['run'];close:()=>void}){
 const [ids,setIds]=useState(memberships(person)),[prefs,setPrefs]=useState<Record<string,ContactPreference>>(()=>Object.fromEntries(directoryGroups(state).map(g=>[g.id,preferences(person,g.id)]))),[direct,setDirect]=useState(person.contactPermissions??{email:false,sms:false});
 return <Dialog open onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Tags & communication preferences</DialogTitle><DialogDescription>{person.name} · Select tags and record email and text permissions.</DialogDescription></DialogHeader><table className="preference-table edit-preferences"><thead><tr><th>Tag</th><th>Email</th><th>Text</th></tr></thead><tbody>{directoryGroups(state).map(g=><tr key={g.id}><td><label className="flex gap-2 items-center"><Checkbox disabled={g.id==='guests'} checked={ids.includes(g.id)} onCheckedChange={v=>setIds(v===true?[...ids,g.id]:ids.filter(id=>id!==g.id))}/>{g.name}</label></td>{(['email','sms'] as const).map(c=><td key={c}><Checkbox aria-label={`${g.name} ${c==='sms'?'text':'email'} permission`} checked={ids.includes(g.id)&&prefs[g.id][c]} disabled={!ids.includes(g.id)} onCheckedChange={v=>setPrefs({...prefs,[g.id]:{...prefs[g.id],[c]:v===true}})}/></td>)}</tr>)}<tr><td>Direct communications</td>{(['email','sms'] as const).map(c=><td key={c}><Checkbox aria-label={`Direct ${c} permission`} checked={direct[c]} onCheckedChange={v=>setDirect({...direct,[c]:v===true})}/></td>)}</tr></tbody></table><p className="text-xs muted">Check a channel when permission is recorded. Direct permissions allow individual messages. Change assimilation enrollment in the person’s profile.</p><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button disabled={busy} onClick={async()=>{if(await run({type:'directory.person',id:person.id,groups:ids,tags:person.tags??[],preferences:prefs,contactPermissions:direct}))close();}}>Save preferences</Button></DialogFooter></DialogContent></Dialog>;
}
