'use client';
import {useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {toast} from 'sonner';
import {csvFields,csvLabels,parsePeopleCsv,guessCsvMapping,previewPeopleCsv,type CsvMapping,type CsvOptions} from '@/lib/pastoral/people-csv';
import type {State,Action} from '@/lib/pastoral/model';

export function PeopleImportTools({state,version,request,onImported}:{state:State;version:number;request:(path:string,init?:RequestInit)=>Promise<Response>;onImported:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[csv,setCsv]=useState(''),[fileName,setFileName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[list,setList]=useState<'prayer'|'guest'>('prayer'),[mapping,setMapping]=useState<CsvMapping>({name:'',firstName:'',lastName:'',phone:'',email:'',firstVisit:''}),[sms,setSms]=useState(false),[email,setEmail]=useState(false),[source,setSource]=useState('');
 const options:CsvOptions={list,mapping,smsPermission:sms,emailPermission:email,consentSource:source};
 const preview=useMemo(()=>{if(!csv)return {headers:[],rows:[],error:''};try{const {headers}=parsePeopleCsv(csv);try{return {headers,rows:previewPeopleCsv(csv,{list,mapping,smsPermission:sms,emailPermission:email,consentSource:source},state),error:''};}catch(e){return {headers,rows:[],error:e instanceof Error?e.message:'Check your columns.'};}}catch(e){return {headers:[],rows:[],error:e instanceof Error?e.message:'Invalid CSV.'};}},[csv,list,mapping,state,sms,email,source]);
 const ready=preview.rows.filter(r=>!r.issue).length,duplicates=preview.rows.filter(r=>r.duplicate).length,invalid=preview.rows.filter(r=>r.issue&&!r.duplicate).length;
 async function save(){setBusy(true);setError('');try{const r=await request('/api/people-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version,csv,options})});const data=await r.json();if(!r.ok){if(r.status===409)await onImported();throw Error(data.error||'Import failed.');}await onImported();setOpen(false);setCsv('');setFileName('');setSms(false);setEmail(false);setSource('');toast.success(`Imported ${ready} people into ${list==='prayer'?'Prayer Chain':'Assimilation'}.`);}catch(e){setError(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);}}
 return <><Button variant="outline" onClick={()=>setOpen(true)}>Import CSV</Button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="sm:max-w-4xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Import people</DialogTitle><DialogDescription>Choose the list, match your columns, and review the records before importing. Existing contacts are skipped and can be updated separately.</DialogDescription></DialogHeader>
 <label className="text-sm font-medium">Import into<Select value={list} onValueChange={v=>{setList(v as 'prayer'|'guest');setSms(false);setEmail(false);setSource('');}}><SelectTrigger aria-label="Import list"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="prayer">Prayer Chain</SelectItem><SelectItem value="guest">Assimilation</SelectItem></SelectContent></Select></label>
 <label className="text-sm font-medium">CSV file<Input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];setError('');setCsv('');setFileName('');if(!file)return;try{if(file.size>500000)throw Error('Choose a CSV under 500 KB.');const text=await file.text();const parsed=parsePeopleCsv(text);setCsv(text);setMapping(guessCsvMapping(parsed.headers));setFileName(file.name);}catch(e){setError(e instanceof Error?e.message:'Unable to read the file.');}}}/></label><p className="text-sm muted">Up to 1,000 people. Include Name (or First Name and Last Name), Phone and/or Email. First Visit is optional; blank dates use today. Prayer-chain imports need phone numbers.</p>
 {fileName&&<p className="text-sm font-medium">{fileName}</p>}
 {!!preview.headers.length&&<div className="grid sm:grid-cols-2 gap-3">{csvFields.map(f=><label className="text-sm" key={f}>{csvLabels[f]}<Select value={mapping[f]||'__none__'} onValueChange={v=>setMapping({...mapping,[f]:v==='__none__'?'':v})}><SelectTrigger aria-label={`CSV column for ${csvLabels[f]}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__none__">Not included</SelectItem>{preview.headers.map(h=><SelectItem key={h} value={h}>{h}</SelectItem>)}</SelectContent></Select></label>)}</div>}
 <div className="rounded-lg border p-4 space-y-3"><h3 className="font-semibold">Contact permission</h3><label className="flex gap-3 text-sm items-start"><Checkbox checked={sms} onCheckedChange={v=>setSms(v===true)}/><span>I confirm all imported people have agreed to receive {list==='prayer'?'prayer-chain':'guest follow-up'} texts.</span></label>{list==='guest'&&<label className="flex gap-3 text-sm items-start"><Checkbox checked={email} onCheckedChange={v=>setEmail(v===true)}/><span>I confirm all imported people have agreed to receive guest follow-up emails.</span></label>}<p className="text-sm muted">Leave unchecked if permission is unknown or mixed, then update each person individually. Existing opt-outs remain in effect.</p>{(sms||list==='guest'&&email)&&<label className="text-sm">How was permission recorded?<Input aria-label="Consent source" maxLength={500} value={source} onChange={e=>setSource(e.target.value)} placeholder="For example: signed prayer-chain signup cards"/></label>}</div>
 {!!preview.rows.length&&<><p className="text-sm font-medium">{ready} new people · {duplicates} duplicates skipped · {invalid} rows to fix</p><div className="max-h-64 overflow-auto border rounded-lg"><Table><TableHeader><TableRow><TableHead>Row</TableHead><TableHead>Name</TableHead><TableHead>Phone / email</TableHead><TableHead>Result</TableHead></TableRow></TableHeader><TableBody>{preview.rows.map(r=><TableRow key={r.row}><TableCell>{r.row}</TableCell><TableCell>{r.name}</TableCell><TableCell>{r.phone}<br/>{r.email}</TableCell><TableCell>{r.issue||'Ready to import'}</TableCell></TableRow>)}</TableBody></Table></div></>}
 {(error||preview.error)&&<p role="alert" className="text-sm text-red-700">{error||preview.error}</p>}<p className="text-sm muted">Importing saves people and list membership. It does not send messages or approve any drafts.</p><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||!ready||!!invalid||!!preview.error||((sms||list==='guest'&&email)&&!source.trim())} onClick={save}>{busy?'Importing…':`Import ${ready} people`}</Button></DialogFooter></DialogContent></Dialog></>;
}

export function AdminPhoneTools({state,busy,run}:{state:State;busy:boolean;run:(a:Action)=>Promise<boolean>}){
 const [phone,setPhone]=useState(state.settings.adminPhone??''),[review,setReview]=useState(false);
 return <section className="panel p-6 mb-6 max-w-3xl"><h2>Admin phone number</h2><p className="text-sm muted mt-2 mb-4">Receives a short notification with a link to review each prayer request in PastoralOS. Website sign-in permissions stay separate.</p><label className="text-sm font-medium">Mobile number<Input type="tel" aria-label="Admin phone number" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(555) 123-4567"/></label><p className="text-sm muted mt-2">Current admin: {state.settings.adminPhone||'Not configured'}</p><Button className="mt-4" disabled={busy||!phone.trim()||phone===state.settings.adminPhone} onClick={()=>setReview(true)}>Review admin change</Button><Dialog open={review} onOpenChange={setReview}><DialogContent><DialogHeader><DialogTitle>Change the admin phone?</DialogTitle><DialogDescription>Review texts will go to {phone}. The previous number will lose text-approval access, and existing review codes will no longer work. Use a number authorized to receive private prayer requests.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setReview(false)}>Cancel</Button><Button disabled={busy} onClick={async()=>{if(await run({type:'settings.admin-phone',phone}))setReview(false);}}>Save admin number</Button></DialogFooter></DialogContent></Dialog></section>;
}
