'use client';
import {useState,useEffect} from 'react';
import {Users,Plus,Clock,Bell,Search,X,PenLine,Copy,CalendarDays,AlertCircle,ChevronLeft,ChevronRight,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {addCalendar,type State,type Action} from '@/lib/pastoral/model';
import {type DeliveryConnection,type CommunicationsState,broadcastStatus} from '@/lib/pastoral/communications';
import {servingData,servingInstant,servingDate,servingTime,serviceLabel,servingRecipientIssue,servingBody,reminderChoices,reminderLabel,type ServicePlan,type MinistryArea} from '@/lib/pastoral/serving';
import './serving-teams.css';

type Props={state:State;busy:boolean;run:(action:Action)=>Promise<boolean>;request:(path:string,init?:RequestInit)=>Promise<Response>};
type EditorProps=Omit<Props,'request'>&{service:ServicePlan;close:()=>void};
const initials=(name:string)=>name.split(' ').map(x=>x[0]).slice(0,2).join('');
const tomorrow=()=>servingDate(addCalendar(new Date(),1,'days'));
export function ServingTeams({state,busy,run,request}:Props){
 const [selected,setSelected]=useState(''),[editingArea,setEditingArea]=useState<MinistryArea|'new'|null>(null),[serviceEditor,setServiceEditor]=useState<'new'|'edit'|'copy'|null>(null),[cancel,setCancel]=useState(false),[connection,setConnection]=useState<DeliveryConnection|null>(null),[connectionError,setConnectionError]=useState(false);
 useEffect(()=>{let active=true;request('/api/delivery-connection').then(async r=>{if(!r.ok)throw Error();const data=await r.json();if(active)setConnection(data);}).catch(()=>{if(active)setConnectionError(true);});return()=>{active=false;};},[request]);
 const services=[...servingData(state).services].sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));
 const service=services.find(s=>s.id===selected||`${s.date}|${s.time}|${s.title}`===selected)??services.find(s=>!s.cancelled&&servingInstant(s.date,s.time)>new Date())??services.at(-1);
 const index=services.findIndex(s=>s.id===service?.id),past=!!service&&servingInstant(service.date,service.time)<=new Date();
 const people=(area:MinistryArea)=>area.personIds.map(id=>state.people.find(p=>p.id===id)).filter(p=>p&&!p.archived);
 const needed=service?.areas.reduce((n,a)=>n+a.needed,0)??0,filled=service?.areas.reduce((n,a)=>n+people(a).length,0)??0;
 const change=(id:string)=>{setSelected(id);setEditingArea(null);};
 const history=(state as CommunicationsState).broadcasts?.filter(b=>b.serving?.serviceId===service?.id)??[];
 return <div className="serving-root">
  {(!connection?.sms)&&<div className="soft-banner serving-notice" role="status"><AlertCircle size={18}/><span>{connectionError?'Text connection could not be checked. Refresh before relying on delivery.':connection?'Text reminders are waiting for the Communications number to be activated. You can build schedules now.':'Checking text delivery…'}</span></div>}
  <div className="serving-toolbar"><div className="serving-service-picker"><Button variant="outline" size="icon" aria-label="Previous service" disabled={index<=0} onClick={()=>change(services[index-1].id)}><ChevronLeft size={17}/></Button><select className="plain-select" aria-label="Service date" value={service?.id??''} onChange={e=>change(e.target.value)}>{!services.length&&<option value="">No services scheduled</option>}{services.map(s=><option key={s.id} value={s.id}>{serviceLabel(s)}{s.cancelled?' · Cancelled':''}</option>)}</select><Button variant="outline" size="icon" aria-label="Next service" disabled={index<0||index===services.length-1} onClick={()=>change(services[index+1].id)}><ChevronRight size={17}/></Button></div><Button variant="outline" disabled={busy} onClick={()=>setServiceEditor('new')}><CalendarDays size={16}/>Add service</Button>{service&&!service.cancelled&&<Button variant="outline" disabled={busy} onClick={()=>setServiceEditor('copy')}><Copy size={16}/>Copy schedule</Button>}</div>
  {!service?<section className="panel serving-empty"><Users size={36}/><h2>Build your first serving schedule</h2><p>Add a service date, create the ministry areas that need covering, and choose volunteers from People.</p><Button onClick={()=>setServiceEditor('new')}><Plus size={16}/>Add your first service</Button></section>:<>
   <div className="serving-heading"><div><h2>{service.title}</h2><p className="muted text-sm mt-1">{service.date} · {servingTime(service.time)} Central {service.cancelled?'· Cancelled':past?'· Past service':''}</p></div><div className="flex gap-2 flex-wrap">{!past&&!service.cancelled&&<><Button variant="ghost" disabled={busy} onClick={()=>setServiceEditor('edit')}><PenLine size={15}/>Edit service</Button><Button variant="ghost" disabled={busy} onClick={()=>setCancel(true)}>Cancel service</Button></>}{service.cancelled&&!past&&<Button variant="outline" disabled={busy} onClick={()=>void run({type:'serving.service.restore',serviceId:service.id,serviceVersion:service.version})}>Restore service</Button>}{!past&&!service.cancelled&&<Button disabled={busy} onClick={()=>setEditingArea('new')}><Plus size={16}/>Add ministry area</Button>}</div></div>
   {service.cancelled&&<div className="soft-banner mb-4">This service is cancelled. Its unsent reminders will not go out.</div>}
   <div className={`serving-layout ${editingArea?'is-editing':''}`}><section><div className="serving-list-heading"><h3>Ministry areas</h3><span className="muted text-sm">{filled} of {needed} spots filled</span></div><div className="serving-area-list">
    {!service.areas.length&&<div className="panel serving-empty"><Users size={28}/><h3>Which ministries need covering?</h3><p>Add areas such as Welcome team, Kids ministry, or Production. Each gets its own arrival time and text reminders.</p>{!past&&!service.cancelled&&<Button variant="outline" onClick={()=>setEditingArea('new')}>Add ministry area</Button>}</div>}
    {service.areas.map(area=>{const assigned=people(area),warnings=area.personIds.map(id=>{const p=state.people.find(p=>p.id===id);return {id,name:p?.name??'Removed person',issue:servingRecipientIssue(state,p)};}).filter(x=>x.issue);return <article key={area.id} className={`panel serving-area ${editingArea!=='new'&&editingArea?.id===area.id?'selected':''}`}><div className="serving-area-title"><span className="stat-icon"><Users size={21}/></span><div className="flex-1"><div className="flex items-center gap-3 flex-wrap"><h3>{area.name}</h3><span className={`badge ${assigned.length<area.needed?'amber':'teal'}`}>{assigned.length} of {area.needed} assigned</span></div><p className="text-sm muted mt-2">{area.description||'No description yet.'}</p></div>{!past&&!service.cancelled&&<Button variant="ghost" size="icon" aria-label={`Edit ${area.name}`} onClick={()=>setEditingArea(area)}><PenLine size={17}/></Button>}</div><div className="serving-meta"><span><Clock size={15}/>Arrive {servingTime(area.arrivalTime)}</span><span><Users size={15}/>{area.needed} volunteers needed</span></div><div className="serving-assignees">{assigned.map(p=>p&&<span className="serving-person" key={p.id}><span className="avatar">{initials(p.name)}</span>{p.name}</span>)}{assigned.length<area.needed&&!past&&!service.cancelled&&<button className="link-button" onClick={()=>setEditingArea(area)}><Plus size={17}/>Add person</button>}</div><p className="serving-reminder-summary"><Bell size={16}/>{area.remindersEnabled?`Text reminders: ${area.reminderMinutes.map(reminderLabel).join(' · ')}`:'Automatic reminders off'}</p>{warnings.length>0&&<div className="serving-warning"><AlertCircle size={15}/><span>{warnings.map(w=>`${w.name}: ${w.issue}`).join(' · ')}</span></div>}</article>;})}
   </div></section>{editingArea&&!past&&!service.cancelled&&<AreaEditor key={service.id+':'+(editingArea==='new'?'new':editingArea.id)} state={state} service={service} area={editingArea==='new'?undefined:editingArea} busy={busy} run={run} close={()=>setEditingArea(null)}/>}</div>
   {history.length>0&&<details className="panel serving-history"><summary>Reminder delivery · {history.length} reminders</summary><p className="muted text-sm my-3">Sent means accepted by the text provider. Skipped and failed reminders show the reason.</p>{history.map(b=><div className="serving-history-row" key={b.id}><div><strong>{state.people.find(p=>p.id===b.serving?.personId)?.name??'Removed person'}</strong><span>{b.subject} · {reminderLabel(b.serving!.minutes)}</span></div><div><strong>{broadcastStatus(b)}</strong><span>{b.skippedRecipients?.map(p=>p.reason).join(', ')||b.targets.map(t=>t.reason).filter(Boolean).join(', ')}</span></div></div>)}</details>}
   <p className="serving-footnote">All times Central. Texts follow church sending hours and each person’s texting permission. Late assignments skip reminder times that have already passed. Replies appear in Communications.</p>
  </>}
  {serviceEditor&&<ServiceEditor key={serviceEditor+service?.id} state={state} service={service} mode={serviceEditor} onSaved={key=>{setSelected(key);setEditingArea(null);}} busy={busy} run={run} close={()=>setServiceEditor(null)}/>}
  {cancel&&service&&<Dialog open onOpenChange={v=>!v&&setCancel(false)}><DialogContent><DialogHeader><DialogTitle>Cancel this service?</DialogTitle><DialogDescription>Unsent reminders stop for {serviceLabel(service)}. You can restore the service later. Texts already sent cannot be recalled.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setCancel(false)}>Keep service</Button><Button variant="destructive" disabled={busy} onClick={async()=>{if(await run({type:'serving.service.cancel',serviceId:service.id,serviceVersion:service.version})){setCancel(false);setEditingArea(null);}}}>Cancel service</Button></DialogFooter></DialogContent></Dialog>}
 </div>;
}
function AreaEditor({state,service,area,busy,run,close}:EditorProps&{area?:MinistryArea}){
 const [name,setName]=useState(area?.name??''),[description,setDescription]=useState(area?.description??''),[arrivalTime,setArrival]=useState(area?.arrivalTime??service.time),[needed,setNeeded]=useState(area?.needed??1),[personIds,setPeople]=useState(area?.personIds??[]),[query,setQuery]=useState(''),[enabled,setEnabled]=useState(area?.remindersEnabled??true),[minutes,setMinutes]=useState(area?.reminderMinutes??[4320,1440]),[remove,setRemove]=useState(false),[initialVersion]=useState(service.version);
 const matching=state.people.filter(p=>!p.archived&&!personIds.includes(p.id)&&query.trim()&&(p.name.toLowerCase().includes(query.toLowerCase())||p.phone.includes(query))).slice(0,8);
 const selected=personIds.map(id=>state.people.find(p=>p.id===id));
 const draft:MinistryArea={id:area?.id??'',name,description,arrivalTime,needed,personIds,assignedAt:area?.assignedAt??{},remindersEnabled:enabled,reminderMinutes:minutes,version:area?.version??0,createdAt:area?.createdAt??new Date().toISOString()};
 const stale=service.version!==initialVersion;
 let preview='Add a ministry name and arrival time to preview the text.';try{if(name&&arrivalTime)preview=servingBody(state,service,draft,selected.find(p=>p)??{name:'Sarah'});}catch{}
 const overlap=service.areas.filter(a=>a.id!==area?.id&&a.personIds.some(id=>personIds.includes(id)));
 return <aside className="panel serving-editor" aria-label="Ministry area settings"><div className="serving-editor-head"><div><h2>{area?'Edit ministry area':'Add ministry area'}</h2><p className="text-sm muted">For this service date</p></div><Button variant="ghost" size="icon" aria-label="Close ministry editor" onClick={close}><X size={19}/></Button></div><form onSubmit={async e=>{e.preventDefault();if(await run({type:'serving.area.save',serviceId:service.id,serviceVersion:initialVersion,areaId:area?.id,name,description,arrivalTime,needed,personIds,remindersEnabled:enabled,reminderMinutes:minutes}))close();}}>
  <label className="field"><span>Area name</span><Input aria-label="Area name" required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Welcome team"/></label><label className="field"><span>What will they do?</span><Textarea aria-label="Ministry description" maxLength={400} rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Greet guests and help them find a seat."/></label><div className="serving-two-fields"><label className="field"><span>Arrival time · Central</span><Input aria-label="Arrival time" type="time" required value={arrivalTime} onChange={e=>setArrival(e.target.value)}/></label><label className="field"><span>People needed</span><Input aria-label="People needed" type="number" min={Math.max(1,personIds.length)} max={50} required value={needed} onChange={e=>setNeeded(Number(e.target.value))}/></label></div>
  <div className="serving-editor-section"><h3>Assign people</h3><label className="serving-search"><Search size={17}/><Input aria-label="Search People for volunteers" autoComplete="off" placeholder="Search People by name…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{query.trim()&&<div className="serving-search-results">{matching.length?matching.map(p=><button type="button" key={p.id} onClick={()=>{setPeople([...personIds,p.id]);setNeeded(Math.max(needed,personIds.length+1));setQuery('');}}><span><strong>{p.name}</strong><small>{servingRecipientIssue(state,p)??p.phone}</small></span><span className="text-teal-700">+ Add</span></button>):<p>No matching people. Add new contacts in People first.</p>}</div>}<small className="muted">Uses your existing People database.</small><div className="serving-selected">{selected.map((p,i)=><div key={personIds[i]}><span><strong>{p?.name??'Removed person'}</strong>{servingRecipientIssue(state,p)&&<small className="text-amber-800">{servingRecipientIssue(state,p)} — reminder will be skipped</small>}</span><button type="button" aria-label={`Remove ${p?.name??'person'} from ministry`} onClick={()=>setPeople(personIds.filter(id=>id!==personIds[i]))}><X size={16}/></button></div>)}</div>{overlap.length>0&&<p className="serving-warning">Some volunteers are also assigned to {overlap.map(a=>a.name).join(', ')}. Check that they can cover both.</p>}</div>
  <div className="serving-editor-section"><div className="flex items-center justify-between gap-3"><label htmlFor="serving-auto"><strong>Automatic text reminders</strong></label><Switch id="serving-auto" checked={enabled} onCheckedChange={setEnabled}/></div><p className="text-sm muted mt-1">For everyone assigned to this area.</p>{enabled&&<><div className="serving-cadence">{minutes.map(n=><span key={n}>{reminderLabel(n)}<button type="button" aria-label={`Remove reminder ${reminderLabel(n)}`} onClick={()=>setMinutes(minutes.filter(x=>x!==n))}><X size={13}/></button></span>)}</div>{minutes.length<4&&<select aria-label="Add reminder timing" className="plain-select w-full" value="" onChange={e=>{if(e.target.value)setMinutes([...minutes,Number(e.target.value)].sort((a,b)=>b-a));}}><option value="">+ Add reminder</option>{reminderChoices.filter(x=>!minutes.includes(x.minutes)).map(x=><option key={x.minutes} value={x.minutes}>{x.label}</option>)}</select>}<p className="text-xs muted mt-2">Before the ministry’s arrival time. Sends automatically; no approval step.</p></>}</div>
  {enabled&&<div className="serving-editor-section"><h3>Message preview</h3><p className="serving-message-preview">{preview}</p><small className="muted">Names and dates are filled in for each volunteer. Text permission is checked again before sending.</small></div>}
  {stale&&<p role="alert" className="serving-warning">This service changed while you were editing. Close and reopen it to use the latest schedule.</p>}<div className="serving-editor-actions">{area&&<Button type="button" variant="ghost" className="text-red-700" onClick={()=>setRemove(true)}><Trash2 size={15}/>Remove area</Button>}<Button type="submit" disabled={busy||stale||!name.trim()||(enabled&&!minutes.length)}>Save area</Button></div>
 </form>{remove&&area&&<Dialog open onOpenChange={v=>!v&&setRemove(false)}><DialogContent><DialogHeader><DialogTitle>Remove {area.name}?</DialogTitle><DialogDescription>This removes the area from this service only and stops its unsent reminders. People records and delivery history stay saved.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setRemove(false)}>Keep area</Button><Button variant="destructive" disabled={busy||stale} onClick={async()=>{if(await run({type:'serving.area.remove',serviceId:service.id,serviceVersion:initialVersion,areaId:area.id}))close();}}>Remove area</Button></DialogFooter></DialogContent></Dialog>}</aside>;
}
function ServiceEditor({service,mode,busy,run,close,onSaved}:Omit<EditorProps,'service'>&{service?:ServicePlan;mode:'new'|'edit'|'copy';onSaved:(key:string)=>void}){
 const [title,setTitle]=useState(mode==='new'?'Sunday Worship':service?.title??''),[date,setDate]=useState(mode==='edit'?service!.date:mode==='copy'?servingDate(addCalendar(servingInstant(service!.date,service!.time),1,'weeks')):tomorrow()),[time,setTime]=useState(mode==='new'?'10:00':service!.time),[count,setCount]=useState(1),[carry,setCarry]=useState(true),[version]=useState(service?.version);
 return <Dialog open onOpenChange={v=>!v&&close()}><DialogContent className="sm:max-w-[530px]"><DialogHeader><DialogTitle>{mode==='new'?'Add service':mode==='copy'?'Copy this schedule':'Edit service'}</DialogTitle><DialogDescription>{mode==='copy'?'Reuse ministry areas and reminder settings. Each copied date can be edited separately.':'Choose when people will be serving. All times use Central time.'}</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();const action:Action=mode==='copy'?{type:'serving.service.copy',serviceId:service!.id,serviceVersion:version,date,count,carryPeople:carry}:{type:'serving.service.save',...(mode==='edit'?{serviceId:service!.id,serviceVersion:version}:{}),title,date,time};if(await run(action)){onSaved(`${date}|${time}|${title}`);close();}}}>{mode!=='copy'&&<label className="field"><span>Service or event name</span><Input aria-label="Service name" required maxLength={100} value={title} onChange={e=>setTitle(e.target.value)}/></label>}<div className="serving-two-fields"><label className="field"><span>{mode==='copy'?'First new date':'Date'}</span><Input aria-label="Service date input" type="date" required min={servingDate(new Date())} value={date} onChange={e=>setDate(e.target.value)}/></label>{mode!=='copy'?<label className="field"><span>Service time · Central</span><Input aria-label="Service time" type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label>:<label className="field"><span>Weekly copies</span><Input aria-label="Number of weekly copies" type="number" min={1} max={26} required value={count} onChange={e=>setCount(Number(e.target.value))}/></label>}</div>{mode==='copy'&&<><div className="flex items-center justify-between gap-3 mb-4"><label htmlFor="carry-serving">Include the same volunteers</label><Switch id="carry-serving" checked={carry} onCheckedChange={setCarry}/></div><p className="text-sm muted mb-4">{count===1?'Creates one new service.':`Creates ${count} services, one week apart.`} {carry?'Assignments and automatic reminder settings carry forward.':'Creates empty assignments for you to fill.'}</p></>}<DialogFooter><Button variant="outline" type="button" onClick={close}>Cancel</Button><Button type="submit" disabled={busy}>{mode==='copy'?'Copy schedule':'Save service'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
