import test from 'node:test';
import assert from 'node:assert/strict';
import {getExpectedTwilioSignature} from 'twilio/lib/webhooks/webhooks.js';
import {handleTwilioWebhook} from '../lib/pastoral/twilio-webhook.ts';
import {initialState} from '../lib/pastoral/model.ts';
const prayer='+18557250789',general='+18555550123',from='+12025550111',account='AC'+'1'.repeat(32),token='test-only';
const inbound='https://example.test/pastoralos-twilio/inbound',status='https://example.test/pastoralos-twilio/status';
const config={PASTORALOS_TWILIO_WEBHOOKS_ENABLED:'true',PASTORALOS_STORAGE:'supabase',PASTORALOS_WORKSPACE_OWNER:'church',TWILIO_AUTH_TOKEN:token,TWILIO_ACCOUNT_SID:account,TWILIO_PHONE_NUMBER:prayer,PASTORALOS_GENERAL_SMS_NUMBER:general,TWILIO_INBOUND_WEBHOOK_URL:inbound,TWILIO_STATUS_WEBHOOK_URL:status};
function database(known=true,conflict=false){let state=initialState();state.inbox=[];state.prayers=[];state.messages=[];state.tasks=[];state.audit=[];state.deliveries=[];state.settings.adminPhone=from;state.people=known?[{...state.people[0],id:'person',phone:from,sample:false}]:[];let version=1,attempts=0;const seen=new Set<string>();return {read:()=>state,attempts:()=>attempts,load:async()=>({state:structuredClone(state),version}),receive:async(_owner:string,v:number,next:typeof state,event:{messageSid:string})=>{attempts++;if(conflict&&attempts===1){version++;return 'conflict' as const;}if(seen.has(event.messageSid))return 'duplicate' as const;assert.equal(v,version);state=structuredClone(next);version++;seen.add(event.messageSid);return 'accepted' as const;},recordStatus:async()=>{}};}
function request(to:string,body:string,extra:Record<string,string>={},kind='inbound'){const params={AccountSid:account,MessageSid:'SM'+'2'.repeat(32),From:from,To:to,Body:body,NumMedia:'0',...extra},url=kind==='status'?status:inbound;return new Request(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Twilio-Signature':getExpectedTwilioSignature(token,url,params)},body:new URLSearchParams(params)});}
test('general replies, prayer wording, and pastor commands remain conversations only',async()=>{for(const body of ['Thanks, see you Sunday!','Please pray for healing.','YES 123','NO 123','EDIT 123: revised']){const db=database();assert.equal((await handleTwilioWebhook(request(general,body),config,db,'inbound')).status,200);assert.equal(db.read().prayers.length,0);assert.equal(db.read().inbox[0].body,body);assert.equal(db.read().inbox[0].line,'general');assert.equal(db.read().inbox[0].to,general);}});
test('the prayer number still creates a request for every ordinary message',async()=>{const db=database();assert.equal((await handleTwilioWebhook(request(prayer,'Thank you'),config,db,'inbound')).status,200);assert.equal(db.read().prayers.length,1);assert.equal(db.read().inbox[0].line,'prayer');});
test('unknown and shared general senders appear privately without assumed identity',async()=>{for(const shared of [false,true]){const db=database(shared);if(shared)db.read().people.push({...db.read().people[0],id:'second'});assert.equal((await handleTwilioWebhook(request(general,'Hello'),config,db,'inbound')).status,200);assert.equal(db.read().inbox[0].personId,'');assert.equal(db.read().inbox[0].from,from);assert.equal(db.read().tasks[0].private,true);assert.equal(db.read().prayers.length,0);}});
test('STOP on the general line suppresses texts without generating a prayer request',async()=>{const db=database();await handleTwilioWebhook(request(general,'STOP'),config,db,'inbound');assert.equal(db.read().smsSuppressions?.[0].phone,from);assert.equal(db.read().people[0].prayerSms,false);assert.equal(db.read().prayers.length,0);});
test('signature and destination validation remain enforced',async()=>{const db=database();const req=request(general,'Hello');req.headers.set('X-Twilio-Signature','invalid');assert.equal((await handleTwilioWebhook(req,config,db,'inbound')).status,403);assert.equal((await handleTwilioWebhook(request('+18555550999','Hello'),config,db,'inbound')).status,400);assert.equal(db.read().inbox.length,0);});
test('retries and a concurrent workspace edit do not duplicate the reply',async()=>{const db=database(true,true);await handleTwilioWebhook(request(general,'Hello'),config,db,'inbound');await handleTwilioWebhook(request(general,'Hello'),config,db,'inbound');assert.equal(db.attempts(),3);assert.equal(db.read().inbox.length,1);assert.equal(db.read().prayers.length,0);});
test('status callbacks accept either owned line, not unrelated numbers',async()=>{const db=database();for(const number of [prayer,general])assert.equal((await handleTwilioWebhook(request(from,'',{From:number,MessageStatus:'delivered'},'status'),config,db,'status')).status,204);assert.equal((await handleTwilioWebhook(request(from,'',{From:'+18555550999',MessageStatus:'delivered'},'status'),config,db,'status')).status,400);});
