import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,applyAction} from './model.ts';
import {applyCommunicationsAction,audience,broadcastIssue,broadcastStatus,memberships,preferences,type CommunicationsState,type Broadcast} from './communications.ts';
import {runBroadcastWorker,deliveryConnection,sendSes,type BroadcastStore} from './broadcast-worker.ts';
const now=new Date('2026-09-19T16:00:00Z'),connection={sms:true,email:true};
function state():CommunicationsState {const s:CommunicationsState=initialState(now);s.people=s.people.slice(0,2).map(p=>({...p,sample:false,stage:'Regular attendee'}));s.directoryGroups=[{id:'weekly',name:'Weekly email'}];s.settings.paused=false;s.settings.guestPaused=true;return s;}
function member(s:CommunicationsState,id='p1',sms=true,email=true){return applyCommunicationsAction(s,{type:'directory.person',id,groups:['weekly'],tags:['Volunteer'],channelPermissions:{sms,email}},'staff',connection,now);}
function draft(s:CommunicationsState,channel='sms'){return applyCommunicationsAction(s,{type:'broadcast.save',subject:'Church update',body:'Join us Sunday.',channel,groupIds:['weekly']},'staff',connection,now);}
function approve(s:CommunicationsState){const b=s.broadcasts![0];return applyCommunicationsAction(s,{type:'broadcast.approve',id:b.id,revision:b.revision,audience:audience(s,b).map(t=>[t.personId,t.destination,t.context])},'staff',connection,now);}
function store(s:CommunicationsState){let state=s,version=1;return {load:async()=>({state:structuredClone(state),version}),save:async(v:number,next:CommunicationsState)=>{if(v!==version)throw Error('CONFLICT');state=structuredClone(next);version++;}} satisfies BroadcastStore;}
const config={twilio:{accountSid:'AC'+'1'.repeat(32),token:'test-only',phone:'+12025550199'}};
const accepted=async(_url:unknown,init?:RequestInit)=>Response.json({sid:'SM'+'2'.repeat(32),account_sid:config.twilio.accountSid,from:config.twilio.phone,to:new URLSearchParams(init?.body as URLSearchParams).get('To')});
test('groups do not grant consent; channels are independent and opt-outs override permission',()=>{let s=member(state(),'p1',false,true);assert.equal(audience(s,{channel:'sms',groupIds:['weekly']}).length,0);assert.equal(audience(s,{channel:'email',groupIds:['weekly']}).length,1);s=member(s);s.smsSuppressions=[{phone:s.people[0].phone,at:now.toISOString(),messageSid:'test'}];assert.equal(audience(s,{channel:'sms',groupIds:['weekly']}).length,0);});
test('overlapping groups and shared destinations are deduplicated',()=>{let s=member(member(state()),'p2');s.people[1].phone=s.people[0].phone;assert.equal(audience(s,{channel:'sms',groupIds:['weekly','weekly']}).length,1);});
test('ordinary edits preserve directory fields',()=>{let s=member(state());s=applyAction(s,{type:'person.save',person:{...s.people[0],name:'Updated name'}},'staff',now);assert.deepEqual(memberships(s.people[0]),['weekly']);assert.equal(preferences(s.people[0],'weekly').email,true);});
test('approval binds exact audience and cannot silently expand',()=>{let s=draft(member(state()));const b=s.broadcasts![0],oldAudience=audience(s,b).map(t=>[t.personId,t.destination,t.context]);s=member(s,'p2');assert.throws(()=>applyCommunicationsAction(s,{type:'broadcast.approve',id:b.id,revision:b.revision,audience:oldAudience},'staff',connection,now),/Recipients changed/);s=approve(s);assert.equal(s.broadcasts![0].targets.length,2);assert.throws(()=>approve(s),/draft changed/);});
test('email cannot be approved until connected; drafts can be saved',()=>{const s=draft(member(state()),'email'),b=s.broadcasts![0];assert.throws(()=>applyCommunicationsAction(s,{type:'broadcast.approve',id:b.id,revision:b.revision},'staff',{sms:true,email:false},now),/SES is not connected/);assert.equal(deliveryConnection({}).email,false);});
test('changes, membership removal, samples, pauses and schedule prevent dispatch',()=>{const s=approve(draft(member(state()))),b=s.broadcasts![0],t=b.targets[0];assert.equal(broadcastIssue(s,b,t,now),null);s.settings.paused=true;assert.match(broadcastIssue(s,b,t,now)!,/paused/);s.settings.paused=false;s.people[0].context++;assert.match(broadcastIssue(s,b,t,now)!,/Contact changed/);s.people[0].context--;s.people[0].sample=true;assert.match(broadcastIssue(s,b,t,now)!,/Sample/);s.people[0].sample=false;b.body='Unapproved change';assert.match(broadcastIssue(s,b,t,now)!,/Message changed after sending was requested/);});
test('scheduled approval supports dates beyond the legacy 48-hour window',()=>{let s=member(state());s=applyCommunicationsAction(s,{type:'broadcast.save',subject:'Next month',body:'Scheduled update',channel:'sms',groupIds:['weekly'],scheduledAt:'2026-10-19T16:00:00Z'},'staff',connection,now);s=approve(s);const b=s.broadcasts![0];assert.equal(broadcastIssue(s,b,b.targets[0],now),'Scheduled for later');});
test('worker sends once; a later run does not resend accepted messages',async()=>{const db=store(approve(draft(member(state()))));let calls=0;const fetcher=(async(...args:Parameters<typeof fetch>)=>{calls++;return accepted(...args);}) as typeof fetch;await runBroadcastWorker(db,config,fetcher,()=>now);await runBroadcastWorker(db,config,fetcher,()=>now);assert.equal(calls,1);assert.equal(broadcastStatus((await db.load()).state.broadcasts![0]),'Sent');});
test('two concurrent workers cannot submit the same target twice',async()=>{const db=store(approve(draft(member(state()))));let calls=0;const fetcher=(async(...args:Parameters<typeof fetch>)=>{calls++;return accepted(...args);}) as typeof fetch;await Promise.all([runBroadcastWorker(db,config,fetcher,()=>now),runBroadcastWorker(db,config,fetcher,()=>now)]);assert.equal(calls,1);});
test('ambiguous sends are marked uncertain and never automatically retried',async()=>{const db=store(approve(draft(member(state()))));let calls=0;const fetcher=(async()=>{calls++;throw Error('timeout');}) as typeof fetch;await runBroadcastWorker(db,config,fetcher,()=>now);await runBroadcastWorker(db,config,fetcher,()=>now);assert.equal(calls,1);assert.equal((await db.load()).state.broadcasts![0].targets[0].status,'uncertain');});
test('provider rejection is an actionable failure, not a sent message',async()=>{const db=store(approve(draft(member(state()))));await runBroadcastWorker(db,config,(async()=>new Response('',{status:400})) as typeof fetch,()=>now);assert.equal((await db.load()).state.broadcasts![0].targets[0].status,'failed');});
test('cancelled and opted-out broadcasts do not reach a provider',async()=>{for(const cancel of [true,false]){let s=approve(draft(member(state())));if(cancel)s=applyCommunicationsAction(s,{type:'broadcast.cancel',id:s.broadcasts![0].id},'staff',connection,now);else s.smsSuppressions=[{phone:s.people[0].phone,at:now.toISOString(),messageSid:'test'}];let calls=0;const db=store(s);await runBroadcastWorker(db,config,(async()=>{calls++;return accepted('');}) as typeof fetch,()=>now);assert.equal(calls,0);}});
test('email request contains a single recipient, sender, reply address and managed unsubscribe',async()=>{const s=approve(draft(member(state()),'email')),b=s.broadcasts![0];let captured:RequestInit|undefined;const ses={region:'us-east-1',accessKeyId:'test',secretAccessKey:'test-only',from:'info@1ag.tv',replyTo:'info@1ag.tv',contactList:'1ag',postalAddress:'Test postal address',enabled:true};const id=await sendSes(b,b.targets[0],ses,(async(_url,init)=>{captured=init;return Response.json({MessageId:'accepted-test'});}) as typeof fetch,now);const body=JSON.parse(captured!.body as string);assert.equal(id,'accepted-test');assert.equal(body.Destination.ToAddresses.length,1);assert.equal(body.FromEmailAddress,'info@1ag.tv');assert.deepEqual(body.ReplyToAddresses,['info@1ag.tv']);assert.equal(body.ListManagementOptions.ContactListName,'1ag');assert.match(body.Content.Simple.Body.Text.Data,/\{\{amazonSESUnsubscribeUrl\}\}/);assert.match((captured!.headers as Record<string,string>).authorization,/AWS4-HMAC-SHA256/);});
