import {applyIncomingSms} from './inbound.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {channelPermissions,setChannelPermissions} from './contact-permissions.ts';
import {initialState,applyAction,eligible,schedulePreview,type Person} from './model.ts';
import {audience,audienceReport,applyCommunicationsAction,broadcastStatus,type CommunicationsState} from './communications.ts';
import {prayerRecipients} from './prayer-approval.ts';
import {runAssimilationWorker} from './assimilation-worker.ts';
import {runBroadcastWorker,type BroadcastStore} from './broadcast-worker.ts';
const now=new Date('2026-09-23T16:00:00Z'),actor='Test',connection={sms:true,email:true};
function state():CommunicationsState{const s:CommunicationsState=initialState(now);s.people=[{...s.people[0],sample:false,assimilation:true,stage:'New guest',stageEnteredAt:now.toISOString(),firstVisit:now.toISOString(),channelPermissions:{sms:true,email:true}}];s.messages=[];s.deliveries=[];s.prayers=[];s.settings.paused=false;s.settings.guestPaused=false;s.settings.start='00:00';s.settings.end='23:59';return s;}
function db(initial:CommunicationsState){let s=initial,v=0;return {load:async()=>({state:structuredClone(s),version:v}),save:async(version:number,next:CommunicationsState)=>{if(version!==v)throw Error('CONFLICT');s=structuredClone(next);v++;}} satisfies BroadcastStore;}
const config={twilio:{accountSid:'AC'+'1'.repeat(32),token:'test',phone:'+12025550199'},ses:{region:'us-east-2',accessKeyId:'test',secretAccessKey:'test',from:'info@1ag.tv',replyTo:'info@1ag.tv',contactList:'church',postalAddress:'Test address',enabled:true}};
const accepted:typeof fetch=async(url,init)=>String(url).includes('amazonaws')?Response.json({MessageId:'email-test'}):Response.json({sid:'SM'+'2'.repeat(32),account_sid:config.twilio.accountSid,from:config.twilio.phone,to:new URLSearchParams(init?.body as URLSearchParams).get('To')});
function approved(channel:'sms'|'email'='sms') {let s=state();s.rules=s.rules.filter(r=>r.id==='welcome');s.rules[0].channel=channel;s=applyAction(s,{type:'prepare'},actor,now);return applyAction(s,{type:'message.approve',id:s.messages[0].id,revision:1},actor,now);}
test('legacy opt-ins carry forward across all sources; explicit global off cannot be resurrected by old tags',()=>{const p={guestSms:false,guestEmail:false,prayerSms:true,contactPermissions:{sms:false,email:true},groupPreferences:{tag:{sms:true,email:false}}};assert.deepEqual(channelPermissions(p),{sms:true,email:true});setChannelPermissions(p,{sms:false,email:false});assert.deepEqual(channelPermissions(p),{sms:false,email:false});assert.equal(p.groupPreferences.tag.sms,true);});
test('one permission controls individuals, tags, prayer and assimilation; tags alone never opt in',()=>{let s=state(),p=s.people[0];s.directoryGroups=[{id:'members',name:'Members'}];s=applyCommunicationsAction(s,{type:'directory.person',id:p.id,groups:['members','guests','prayer'],tags:[],channelPermissions:{sms:false,email:true}},actor,connection,now);p=s.people[0];assert.equal(audience(s,{channel:'sms',groupIds:['members'],personIds:[p.id]}).length,0);assert.equal(prayerRecipients(s).length,0);assert.equal(applyAction(s,{type:'prepare'},actor,now).messages.length,0);assert.equal(audience(s,{channel:'email',groupIds:['members']}).length,1);s=applyCommunicationsAction(s,{type:'directory.person',id:p.id,groups:['members','guests'],tags:[]},actor,connection,now);assert.deepEqual(channelPermissions(s.people[0]),{sms:false,email:true});});
test('prayer can never become an email broadcast, while a member can receive ordinary email',()=>{const s=state(),p=s.people[0];p.prayerMember=true;assert.throws(()=>applyCommunicationsAction(s,{type:'broadcast.save',channel:'email',groupIds:['prayer'],subject:'News',body:'Hello'},actor,connection,now),/text messages only/);assert.equal(audience(s,{channel:'email',groupIds:[],personIds:[p.id]}).length,1);const m={...approved().messages[0],program:'prayer' as const,channel:'email' as const};assert.equal(eligible(s,m,{personId:p.id,destination:p.email,context:p.context}),'Prayer chain uses text messages only');});
test('send records names and reasons for omitted contacts, including an entirely skipped audience',async()=>{for(const allSkipped of [false,true]){const s=state(),p=s.people[0];p.channelPermissions={sms:!allSkipped,email:true};s.people.push({...p,id:'missing',name:'No Permission',phone:'+12025550111',channelPermissions:{sms:false,email:true}},{...p,id:'no-phone',name:'No Phone',phone:''});const selection={channel:'sms' as const,personIds:s.people.map(p=>p.id),groupIds:[]};const report=audienceReport(s,selection);const result=applyCommunicationsAction(s,{type:'broadcast.send',...selection,subject:'Test',body:'Hello',audience:report.targets.map(t=>[t.personId,t.destination,t.context])},actor,connection,now);assert.equal(result.broadcasts![0].skippedRecipients!.length,allSkipped?3:2);assert.equal(result.broadcasts![0].skippedRecipients!.find(p=>p.name==='No Permission')?.reason,'No text permission');let calls=0;const store=db(result);await runBroadcastWorker(store,config,async(...args)=>{calls++;return accepted(...args);},()=>now);assert.equal(calls,allSkipped?0:1);assert.equal(broadcastStatus((await store.load()).state.broadcasts![0]),allSkipped?'Not sent':'Finished with skips');}});
test('scheduler prepares without approval or enrollment side effects and does not duplicate drafts',async()=>{const s=state();s.people.push({...s.people[0],id:'not-guest',assimilation:false});const store=db(s);let calls=0;const fetcher:typeof fetch=async()=>{calls++;throw Error('Must not send');};await runAssimilationWorker(store,config,fetcher,()=>now);await runAssimilationWorker(store,config,fetcher,()=>now);assert.equal((await store.load()).state.messages.length,1);assert.equal(calls,0);});
test('approved assimilation SMS and email use real provider paths exactly once, including concurrent workers',async()=>{for(const channel of ['sms','email'] as const){const store=db(approved(channel));let calls=0;const fetcher:typeof fetch=async(...args)=>{calls++;return accepted(...args);};await Promise.all([runAssimilationWorker(store,config,fetcher,()=>now),runAssimilationWorker(store,config,fetcher,()=>now)]);await runAssimilationWorker(store,config,fetcher,()=>now);assert.equal(calls,1);assert.equal((await store.load()).state.deliveries[0].status,'sent');}});
test('revocation, STOP, sample, stage change, edited step, old approval and expiration prevent assimilation sends',async()=>{const mutations=[(s:CommunicationsState)=>{s.people[0].channelPermissions!.sms=false;},(s:CommunicationsState)=>{s.smsSuppressions=[{phone:s.people[0].phone,at:now.toISOString(),messageSid:'test'}];},(s:CommunicationsState)=>{s.people[0].sample=true;},(s:CommunicationsState)=>{s.people[0].stage='Welcome';},(s:CommunicationsState)=>{s.rules[0].enabled=false;},(s:CommunicationsState)=>{delete s.messages[0].approval!.sendRequested;},(s:CommunicationsState)=>{s.messages[0].approval!.expiresAt=now.toISOString();}];for(const change of mutations){const s=approved();change(s);const store=db(s);let calls=0;await runAssimilationWorker(store,config,async()=>{calls++;throw Error('Blocked');},()=>now);assert.equal(calls,0);assert.equal((await store.load()).state.deliveries[0].status,'suppressed');}});
test('pause, sending hours and channel connection hold assimilation for later',async()=>{for(const mode of ['pause','hours','connection']){const s=approved();if(mode==='pause')s.settings.paused=true;if(mode==='hours'){s.settings.start='20:00';s.settings.end='21:00';}const store=db(s);let calls=0;await runAssimilationWorker(store,mode==='connection'?{}:config,async()=>{calls++;throw Error('Blocked');},()=>now);assert.equal(calls,0);assert.equal((await store.load()).state.deliveries[0].status,'queued');}});
test('ambiguous assimilation provider responses never automatically resend',async()=>{const store=db(approved());let calls=0;const fail:typeof fetch=async()=>{calls++;throw Error('timeout');};await runAssimilationWorker(store,config,fail,()=>now);await runAssimilationWorker(store,config,fail,()=>now);assert.equal(calls,1);assert.equal((await store.load()).state.deliveries[0].status,'uncertain');});
test('steps can be added, renamed, rescheduled and switch channel; editing revokes pending approvals',()=>{let s=approved();s=applyAction(s,{type:'rule.save',title:'A new email step',stage:'Registered',days:2,channel:'email',template:'Hello {firstName}',enabled:true,recurrence:{frequency:'weekly',interval:2,duration:3,durationUnit:'months'}},actor,now);const rule=s.rules.at(-1)!;assert.equal(rule.version,1);s=applyAction(s,{type:'rule.save',...rule,id:'welcome',title:'Welcome email'},actor,now);assert.equal(s.messages[0].status,'held');assert.equal(s.messages[0].approval,undefined);assert.equal(s.rules[0].channel,'email');assert.equal(s.deliveries[0].status,'cancelled');});
test('monthly and daily repeat dates preserve Central time over short months and DST',()=>{assert.deepEqual(schedulePreview('2026-01-31T15:00:00.000Z',0,{frequency:'monthly',interval:1,duration:3,durationUnit:'months'},3).dates,['2026-01-31T15:00:00.000Z','2026-02-28T15:00:00.000Z','2026-03-31T14:00:00.000Z']);assert.deepEqual(schedulePreview('2026-03-07T15:00:00.000Z',0,{frequency:'daily',interval:1,duration:3,durationUnit:'days'},3).dates,['2026-03-07T15:00:00.000Z','2026-03-08T14:00:00.000Z','2026-03-09T14:00:00.000Z']);});

test('STOP disables the global text switch for every shared-number profile without affecting email',()=>{const s=state();s.people.push({...s.people[0],id:'shared'});const event={accountSid:'ACtest',messageSid:'SMtest',from:s.people[0].phone,to:'+12025550199',body:'STOP',optOut:'STOP',mediaCount:0};const stopped=applyIncomingSms(s,event,now);for(const p of stopped.people)assert.deepEqual(channelPermissions(p),{sms:false,email:true});assert.equal(stopped.smsSuppressions?.length,1);const again=applyIncomingSms(stopped,event,now);assert.deepEqual(again,stopped);});
test('completed daily occurrence allows the next day; editing a step does not reopen an already submitted message',async()=>{let s=state();s.rules=s.rules.filter(r=>r.id==='welcome');s.rules[0].recurrence={frequency:'daily',interval:1,duration:1,durationUnit:'months'};s=applyAction(s,{type:'prepare'},actor,now);s=applyAction(s,{type:'message.approve',id:s.messages[0].id,revision:1},actor,now);const store=db(s);await runAssimilationWorker(store,config,accepted,()=>now);const sent=(await store.load()).state;const rule=sent.rules[0];const edited=applyAction(sent,{type:'rule.save',...rule,title:'Revised welcome'},actor,now);assert.equal(edited.messages[0].status,'approved');await runAssimilationWorker(store,config,accepted,()=>new Date('2026-09-24T16:00:00Z'));assert.equal((await store.load()).state.messages.length,2);assert.equal((await store.load()).state.messages[0].status,'pending');const held=applyAction(sent,{type:'message.hold',id:sent.messages[0].id},actor,now);const reopened=applyAction(held,{type:'message.reopen',id:held.messages[0].id},actor,now);assert.throws(()=>applyAction(reopened,{type:'message.approve',id:reopened.messages[0].id,revision:reopened.messages[0].revision},actor,now),/already submitted/);});
