import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialState,applyAction,isAssimilating,eligible} from './model.ts';
import {applyCommunicationsAction,audience,broadcastFingerprint,broadcastIssue,memberships,type CommunicationsState} from './communications.ts';
import {starterDesign,newBlock,renderEmail,validateDesign,centralDate,centralInput} from './email-design.ts';
import {sendSes} from './broadcast-worker.ts';
import {readEmailImage} from './email-image.ts';
const now=new Date('2026-09-19T15:00:00Z'),connection={sms:true,email:true},actor='Test';
function empty(){const s=initialState();s.people=[];s.messages=[];s.deliveries=[];return s;}
function person(enroll?:boolean){return applyAction(empty(),{type:'person.save',person:{name:'Test Person',phone:'+15555550123',email:'test@example.com',guestSms:true,guestEmail:true,prayerMember:true,prayerSms:true},...(enroll===undefined?{}:{enroll})},actor,now);}
test('new contacts and prayer contacts are not guests, even with guest permissions',()=>{for(const v of [undefined,false]){const s=person(v);assert.equal(isAssimilating(s.people[0]),false);assert.equal(s.people[0].stage,'Contact');assert.deepEqual(memberships(s.people[0]),['prayer']);assert.equal(applyAction(s,{type:'prepare'},actor,now).messages.length,0);}});
test('explicit enrollment starts one welcome; removal holds all future guest sending without changing prayer permissions',()=>{let s=person();const p=s.people[0];s=applyAction(s,{type:'person.enrollment',id:p.id,enroll:true},actor,now);assert.equal(s.people[0].stage,'New guest');assert.equal(s.messages.length,1);s=applyAction(s,{type:'person.enrollment',id:p.id,enroll:true},actor,now);assert.equal(s.messages.length,1);s=applyAction(s,{type:'person.enrollment',id:p.id,enroll:false},actor,now);assert.equal(s.messages[0].status,'cancelled');assert.equal(s.people[0].prayerSms,true);assert.equal(eligible(s,s.messages[0],s.messages[0].targets[0]),'Not enrolled in assimilation');});
test('editing a contact can enroll atomically and subsequent ordinary edits preserve enrollment',()=>{let s=person();s=applyAction(s,{type:'person.save',person:s.people[0],enroll:true},actor,now);assert.equal(s.messages.length,1);s=applyAction(s,{type:'person.save',person:{...s.people[0],name:'Updated'}},actor,now);assert.equal(isAssimilating(s.people[0]),true);});
test('individual recipients use the same global permission, deduplicate with tags, and respect STOP',()=>{const s=person() as CommunicationsState,p=s.people[0];assert.equal(audience(s,{channel:'sms',groupIds:[],personIds:[p.id]}).length,1);Object.assign(p,{contactPermissions:{email:true,sms:true}});assert.equal(audience(s,{channel:'sms',groupIds:['prayer'],personIds:[p.id]}).length,1);s.smsSuppressions=[{phone:p.phone,at:now.toISOString(),messageSid:'test'}];assert.equal(audience(s,{channel:'sms',groupIds:['prayer'],personIds:[p.id]}).length,0);});
test('send now saves and approves exact content atomically; stale audience rejects entire action',()=>{const s=person(),targets=audience(s,{channel:'sms',groupIds:['prayer']});const action={type:'broadcast.send',channel:'sms',subject:'Hello',body:'A test message',groupIds:['prayer'],audience:targets.map(t=>[t.personId,t.destination,t.context])};assert.throws(()=>applyCommunicationsAction(s,{...action,audience:[]},actor,connection,now),/Recipients changed/);assert.equal((s as CommunicationsState).broadcasts,undefined);const next=applyCommunicationsAction(s,action,actor,connection,now),b=next.broadcasts![0];assert.equal(b.status,'queued');assert.equal(b.approval!.fingerprint,broadcastFingerprint(b));});
test('email blocks escape text and reject unsafe URLs, malformed styles, duplicate IDs, excess blocks',()=>{const design=starterDesign();design.blocks[0].text='<script>alert("hello")</script>';const html=renderEmail(design).html;assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));for(const url of ['javascript:alert(1)','data:image/svg+xml,hi','http://example.com','https://name:secret@example.com']){const d=starterDesign();d.blocks[2].url=url;assert.throws(()=>validateDesign(d));}assert.throws(()=>validateDesign({...design,background:'red;display:none'}));assert.throws(()=>validateDesign({...design,blocks:[design.blocks[0],design.blocks[0]]}));assert.throws(()=>validateDesign({...design,blocks:Array.from({length:61},()=>newBlock('text'))}));});
test('saved template and HTML broadcasts bind design and individual audience to approval',()=>{const s=person(),design=starterDesign();let next=applyCommunicationsAction(s,{type:'broadcast.template',name:'Newsletter',design},actor,connection,now);assert.equal(next.emailTemplates?.length,1);next=applyCommunicationsAction(next,{type:'broadcast.save',channel:'email',subject:'News',body:'ignored',design,groupIds:[],personIds:[s.people[0].id]},actor,connection,now);const b=next.broadcasts![0];assert.equal(b.body,renderEmail(design).text);const original=broadcastFingerprint(b);b.design!.blocks[0].text='Changed';assert.notEqual(broadcastFingerprint(b),original);});
test('SES sends the approved HTML with plain text and unsubscribe in both',async()=>{const s=person();const next=applyCommunicationsAction(s,{type:'broadcast.save',channel:'email',subject:'News',body:'',design:starterDesign(),groupIds:[],personIds:[s.people[0].id]},actor,connection,now);let payload:any;await sendSes(next.broadcasts![0],{personId:'p',context:1,destination:'test@example.com',status:'pending'},{region:'us-east-1',accessKeyId:'test',secretAccessKey:'test',from:'info@1ag.tv',replyTo:'info@1ag.tv',enabled:true,contactList:'church',postalAddress:'Test address'},async(_url,init)=>{payload=JSON.parse(String(init?.body));return Response.json({MessageId:'test'});},now);assert.ok(payload.Content.Simple.Body.Html.Data.includes('This week at 1AG'));assert.ok(payload.Content.Simple.Body.Html.Data.includes('{{amazonSESUnsubscribeUrl}}'));assert.ok(payload.Content.Simple.Body.Text.Data.includes('{{amazonSESUnsubscribeUrl}}'));});
test('Central scheduler accounts for DST, invalid calendar dates, and nonexistent times',()=>{assert.equal(centralDate('2026-09-20T09:00'),'2026-09-20T14:00:00.000Z');assert.equal(centralDate('2026-12-20T09:00'),'2026-12-20T15:00:00.000Z');assert.throws(()=>centralDate('2026-03-08T02:30'));assert.throws(()=>centralDate('2026-02-30T09:00'));assert.equal(centralInput(centralDate('2026-09-20T09:00')),'2026-09-20T09:00');});
test('image uploads reject SVG, incorrect file headers, and oversized streams',async()=>{await assert.rejects(()=>readEmailImage(new Request('https://example.com',{method:'POST',headers:{'content-type':'image/svg+xml'},body:'<svg/>'})));await assert.rejects(()=>readEmailImage(new Request('https://example.com',{method:'POST',headers:{'content-type':'image/png'},body:'<script>not an image</script>'})));await assert.rejects(()=>readEmailImage(new Request('https://example.com',{method:'POST',headers:{'content-type':'image/png'},body:new Uint8Array(3*1024*1024+1)})),/under 3 MB/);});
test('database JSON object key reordering preserves an email approval, but changed content does not',()=>{const s=person() as CommunicationsState;Object.assign(s.people[0],{contactPermissions:{email:true,sms:true}});const selection={channel:'email' as const,groupIds:[],personIds:[s.people[0].id]};const targets=audience(s,selection);const next=applyCommunicationsAction(s,{type:'broadcast.send',...selection,subject:'News',body:'',design:starterDesign(),audience:targets.map(t=>[t.personId,t.destination,t.context])},actor,connection,now);function reorder(x:any):any{return Array.isArray(x)?x.map(reorder):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).reverse().map(([k,v])=>[k,reorder(v)])):x;}const loaded=reorder(next) as CommunicationsState,b=loaded.broadcasts![0];assert.equal(b.approval!.fingerprint,broadcastFingerprint(b));assert.equal(broadcastIssue(loaded,b,b.targets[0],now),null);b.design!.blocks[0].text='Different';assert.equal(broadcastIssue(loaded,b,b.targets[0],now),'Message changed after sending was requested');});
test('email delivery remains blocked without SES, including atomic send and scheduled send',()=>{const s=person(),targets=audience(s,{channel:'sms',groupIds:['prayer']});assert.throws(()=>applyCommunicationsAction(s,{type:'broadcast.send',channel:'email',subject:'News',design:starterDesign(),groupIds:[],personIds:[s.people[0].id],scheduledAt:'2026-09-21T15:00:00Z',audience:targets.map(t=>[t.personId,t.destination,t.context])},actor,{sms:true,email:false},now),/not connected/);assert.equal((s as CommunicationsState).broadcasts,undefined);});
test('paired graphics survive saving, render side by side, stack on mobile, and retain plain text links',()=>{const b=newBlock('image-pair');b.images=[{src:'https://example.com/left.png',alt:'Left graphic',href:'https://example.com/left'},{src:'https://example.com/right.png',alt:'Right graphic',href:''}];const design={...starterDesign('blank'),blocks:[b]};const saved=applyCommunicationsAction(person(),{type:'broadcast.save',channel:'email',subject:'Two images',groupIds:[],design},actor,connection,now).broadcasts![0];assert.deepEqual(saved.design!.blocks[0].images,b.images);const {html,text}=renderEmail(saved.design!);assert.equal((html.match(/class="email-column" width="50%"/g)??[]).length,2);assert.ok(html.includes('@media(max-width:480px)'));assert.ok(html.includes('display:block!important;width:100%!important'));assert.ok(html.includes('src="https://example.com/left.png"'));assert.ok(html.includes('href="https://example.com/left"'));assert.ok(text.includes('Left graphic\nhttps://example.com/left'));assert.ok(text.includes('Right graphic\nhttps://example.com/right.png'));const fp=broadcastFingerprint(saved);saved.design!.blocks[0].images![1].src='https://example.com/replacement.png';assert.notEqual(broadcastFingerprint(saved),fp);});
test('paired graphics validate both URLs and descriptions without changing legacy blocks',()=>{const b=newBlock('image-pair'),d={...starterDesign('blank'),blocks:[b]};b.images![1].src='javascript:alert(1)';assert.throws(()=>validateDesign(d),/https/);b.images![1].src='https://example.com/right.png';b.images![0].href='data:text/html,<script>';assert.throws(()=>validateDesign(d),/https/);b.images![0].href='';b.images![0].alt='" onerror="alert(1)<script>';b.images![0].src='https://example.com/left.png';assert.ok(renderEmail(d).html.includes('&quot; onerror=&quot;alert(1)&lt;script&gt;'));assert.throws(()=>validateDesign({...d,blocks:[{...b,images:[]}]}),/two images/);const old=starterDesign();assert.deepEqual(validateDesign(old),old);});
